"use client";

import { useRouter } from "next/navigation";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-[16px] font-bold text-on-surface mb-3">{title}</h2>
      <div className="space-y-3">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  const router = useRouter();
  return (
    <div className="min-h-dvh bg-surface">
      <div className="max-w-2xl mx-auto px-6 py-10">
        <div className="mb-8">
          <button
            onClick={() => window.history.length > 1 ? router.back() : router.replace("/")}
            className="text-[13px] text-on-surface-variant/60 hover:text-on-surface-variant mb-6 inline-block cursor-pointer"
          >
            ← Back
          </button>
          <h1 className="text-[24px] font-extrabold text-on-surface font-[family-name:var(--font-manrope)] mb-2">
            Terms &amp; Conditions
          </h1>
          <p className="text-[13px] text-on-surface-variant/60">Last updated: June 2026</p>
        </div>

        <div className="space-y-8 text-[14px] text-on-surface-variant leading-relaxed">

          <p>
            This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder as applicable. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </p>

          <Section title="General">
            <p>
              www.betterhalforyou.com (the &quot;Website&quot;) is owned and operated by Mosaic Wellness Private Limited (the &quot;Company&quot; / &quot;We&quot; / &quot;Us&quot;), having its registered office at Lodha iThink, 6th Floor, Chirak Nagar, Thane West, Thane, Maharashtra – 400601.
            </p>
            <p>
              Use of the Website is offered to You subject to acceptance of all the terms, conditions and notices contained herein. By using this Website, You agree that You have read, understood and agreed to be bound by these Terms, the Website&apos;s Privacy Policy, and all applicable laws and regulations in India.
            </p>
            <p>
              For the purpose of these Terms, &apos;You&apos; or &apos;User&apos; means any natural or legal person who has agreed to become a buyer on the Website by providing account information while registering as a registered User.
            </p>
          </Section>

          <Section title="Products and Services">
            <p>
              The Website is a platform that facilitates online purchase of wellness and health-related products and services offered by the Company. The Company reserves the right to change or modify these Terms at any time at its sole discretion. Changes are effective immediately upon posting. Your continued use of the Website confirms acceptance of such changes.
            </p>
            <p>
              The Company makes no warranty that the Services will meet Your requirements or be uninterrupted, timely, secure, or error-free.
            </p>
          </Section>

          <Section title="Eligibility">
            <p>
              Use of the Website is available only to persons who can form legally binding contracts under the Indian Contract Act, 1872. Minors under 18 may use the Website only through a legal guardian. The Company reserves the right to terminate access at any time without reason.
            </p>
          </Section>

          <Section title="User Account, Password and Security">
            <p>
              You are responsible for maintaining the confidentiality of your account information and for all activities that occur under your account. Notify the Company immediately of any unauthorised use. You shall ensure that account information is true, complete, accurate and up-to-date.
            </p>
          </Section>

          <Section title="Pricing and Payment">
            <p>
              Your relationship with the Company is on a principal-to-principal basis. By placing an order on the Website, You enter into a legally binding and enforceable contract to purchase the Products on the payment mode specified. The Company reserves the right to refuse to process orders from Users with a prior history of questionable charges or breach of any agreements.
            </p>
          </Section>

          <Section title="Wallet">
            <p>
              The Company may offer a Wallet feature for payments. Wallet cashbacks are treated as discounts on purchases. Wallet Money can be recharged using payment options available on the Website. Wallet balances cannot be withdrawn to a bank account or credited to any pre-paid instrument. Wallet Money expires 1 year from date of credit; Wallet Cashbacks expire 6 months from date of credit. Wallets are available only to resident Indians aged 18 and above, are non-transferable, and have a maximum balance of ₹10,000 at any time.
            </p>
          </Section>

          <Section title="Cancellation, Returns and Refund Policy">
            <p><strong>Cancellation:</strong> An order can be cancelled through the Website before it has been dispatched for delivery.</p>
            <p><strong>Returns:</strong> Any product or order cannot be returned and will not be accepted after payment is made.</p>
            <p><strong>Refunds:</strong> Once a refund has been initiated for eligible cases, the amount is expected to reflect in your account within 7 working days.</p>
          </Section>

          <Section title="Intellectual Property Rights">
            <p>
              The Website and all its content — including text, graphics, user interfaces, artwork and code — are owned and controlled by the Company and are protected by copyright, patent and trademark laws. The trademarks, logos and service marks displayed on the Website are the property of the Company or their respective owners. You are not permitted to use these without prior consent.
            </p>
          </Section>

          <Section title="Disclaimer of Warranties &amp; Liabilities">
            <p>
              The Website, services and materials are provided on an &quot;as is&quot; basis without warranty of any kind. The Company shall not be liable for any loss, damage, or interruption arising from use of the Website. The Company&apos;s entire liability to You shall not exceed the refund of the money charged for the specific product or service under which the liability arises.
            </p>
          </Section>

          <Section title="Governing Law">
            <p>
              These Terms and all transactions on the Website shall be governed by the laws of India. All disputes shall be subject to the exclusive jurisdiction of the courts at Mumbai, India.
            </p>
          </Section>

          <Section title="Grievance Redressal">
            <p>
              For any order-related issues, reach out via chat support on the Website or write to us at{" "}
              <a href="mailto:support@betterhalforyou.com" className="text-primary-container underline">support@betterhalforyou.com</a>.
            </p>
            <p>If You have unresolved grievances, contact our Grievance Officer:</p>
            <div className="bg-surface-container rounded-xl p-4 space-y-1">
              <p className="font-semibold text-on-surface">Mr. Mridul Muralidharan</p>
              <p>Senior Director, Mosaic Wellness Private Limited</p>
              <p>Lodha iThink, 6th Floor, Chirak Nagar, Thane West, Thane, Maharashtra – 400601</p>
              <p>Phone: +91 8128688128</p>
              <p>Email: <a href="mailto:grievances@mosaicwellness.in" className="text-primary-container underline">grievances@mosaicwellness.in</a></p>
              <p>Mon – Sat, 09:00 – 18:00</p>
            </div>
            <p>
              The Grievance Officer shall acknowledge complaints within 48 hours and endeavour to resolve within 30 days, in compliance with the Information Technology Act, 2000 and the Consumer Protection (E-Commerce) Rules, 2020.
            </p>
          </Section>

        </div>
      </div>
    </div>
  );
}
