import type { Product } from "@/lib/protocolEngine";

export const BW_PRODUCTS: Product[] = [
  // ── HAIR ──────────────────────────────────────────────────────
  {
    id: "hair-health-gummies-xp",
    brand: "Be Bodywise",
    name: "Biotin Hair Gummies (30)",
    price: 499,
    mrp: 499,
    concern: ["hair"],
    gender: ["female"],
    segment: ["female-18-25", "female-25-35", "female-35-plus"],
    followUp: ["hair fall", "thinning", "hair health"],
    category: "hair",
    baseScore: 88,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/hair-health-gummies/4%25AHABHARollOn%20%281%29_hk8vt2.jpg?tr=w-600",
    url: "https://bebodywise.com/hair-health-gummies-xp",
    rating: 4.5,
    reviewCount: 1130,
  },
  {
    id: "biotin-hair-gummies-breastfeeding-moms-30n",
    brand: "Be Bodywise",
    name: "Hair Gummies for Postpartum Hair Fall (30N)",
    price: 499,
    mrp: 499,
    concern: ["hair"],
    gender: ["female"],
    segment: ["female-25-35", "female-35-plus"],
    followUp: ["postpartum", "breastfeeding", "hair fall"],
    category: "hair",
    baseScore: 63,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/biotin-hair-gummies-breastfeeding-moms-30n/4%25AHABHARollOn%20%281%29_4k112i.jpg?tr=w-600",
    url: "https://bebodywise.com/biotin-hair-gummies-breastfeeding-moms-30n",
    rating: 4.5,
    reviewCount: 1130,
  },
  {
    id: "hair-fall-control-shampoo",
    brand: "Be Bodywise",
    name: "Keratin Shampoo for Hair Fall",
    price: 499,
    mrp: 499,
    concern: ["hair"],
    gender: ["female"],
    segment: ["female-18-25", "female-25-35", "female-35-plus"],
    followUp: ["hair fall", "thinning"],
    category: "hair",
    baseScore: 82,
    image: "https://i.mscwlns.co/media/misc/others/AppThumbnail_KerShampoo_kfz6tt.jpg?tr=w-600",
    url: "https://bebodywise.com/hair-fall-control-shampoo",
    rating: 4.4,
    reviewCount: 169,
  },
  {
    id: "hair-strengthening-serum",
    brand: "Be Bodywise",
    name: "Hair Strengthening Serum",
    price: 499,
    mrp: 499,
    concern: ["hair"],
    gender: ["female"],
    segment: ["female-18-25", "female-25-35", "female-35-plus"],
    followUp: ["thinning", "breakage", "hair fall"],
    category: "hair",
    baseScore: 85,
    image: "https://i.mscwlns.co/media/misc/others/AppThumbnail_HairStrenghteningSerum_100ml_3nh8dn.jpg?tr=w-600",
    url: "https://bebodywise.com/hair-strengthening-serum",
    rating: 4.8,
    reviewCount: 95,
  },
  {
    id: "hair-growth-oil",
    brand: "Be Bodywise",
    name: "Hair Growth Oil",
    price: 449,
    mrp: 449,
    concern: ["hair"],
    gender: ["female"],
    segment: ["female-18-25", "female-25-35", "female-35-plus"],
    followUp: ["hair fall", "growth", "scalp"],
    category: "hair",
    baseScore: 80,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1611808250/staging/products/hair-nourish/carousel/Hair-Oil.png?tr=w-400",
    url: "https://bebodywise.com/hair-growth-oil",
    rating: 4.8,
    reviewCount: 21,
  },
  {
    id: "1-ketoconazole-dandruff-shampoo-250ml",
    brand: "Be Bodywise",
    name: "1% Ketoconazole Anti-Dandruff Shampoo (250ml)",
    price: 499,
    mrp: 499,
    concern: ["hair"],
    gender: ["female"],
    segment: ["female-18-25", "female-25-35", "female-35-plus"],
    followUp: ["dandruff", "scalp", "itchy"],
    category: "hair",
    baseScore: 83,
    image: "https://i.mscwlns.co/media/misc/others/AppThumbnail_KetoShampoo_Big_fyk2qa.jpg?tr=w-600",
    url: "https://bebodywise.com/1-ketoconazole-dandruff-shampoo-250ml",
    rating: 4.5,
    reviewCount: 31,
  },
  {
    id: "hair-health-gummies-for-teens-30",
    brand: "Be Bodywise",
    name: "Hair Health Gummies for Teens (30N)",
    price: 499,
    mrp: 699,
    concern: ["hair"],
    gender: ["female"],
    segment: ["female-18-25"],
    followUp: ["hair fall", "thinning", "teen"],
    category: "hair",
    baseScore: 84,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/hair-health-gummies-for-teens-30/For%20%287%29_1i9gvv.png?tr=w-600",
    url: "https://bebodywise.com/hair-health-gummies-for-teens-30",
    rating: 4.6,
    reviewCount: 14,
  },
  {
    id: "effervescent-biotin-tablets-pack-2",
    brand: "Be Bodywise",
    name: "Effervescent Biotin Tablets - Pack of 2",
    price: 499,
    mrp: 598,
    concern: ["hair"],
    gender: ["female"],
    segment: ["female-18-25", "female-25-35", "female-35-plus"],
    followUp: ["hair fall", "greying", "thinning"],
    category: "hair",
    baseScore: 78,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1638857946/staging/products/effervescent-biotin-tablets/PACK%20OF%202/pack-of-2.png?tr=w-800",
    url: "https://bebodywise.com/effervescent-biotin-tablets-pack-2",
    rating: 4.5,
    reviewCount: 19,
  },

  // ── SKIN / FACE ───────────────────────────────────────────────
  {
    id: "skin-health-gummies",
    brand: "Be Bodywise",
    name: "Skin Health Gummies (30)",
    price: 499,
    mrp: 599,
    concern: ["skin"],
    gender: ["female"],
    segment: ["female-18-25", "female-25-35", "female-35-plus"],
    followUp: ["dullness", "glow", "pigmentation"],
    category: "skin",
    baseScore: 85,
    image: "https://i.mscwlns.co/media/misc/others/AppThumbnail_Collagen30_a08cuw.jpg?tr=w-600",
    url: "https://bebodywise.com/skin-health-gummies",
    rating: 4.4,
    reviewCount: 38,
  },
  {
    id: "skin-clarifying",
    brand: "Be Bodywise",
    name: "10% Niacinamide Serum",
    price: 599,
    mrp: 599,
    concern: ["skin"],
    gender: ["female"],
    segment: ["female-18-25", "female-25-35"],
    followUp: ["acne", "oily", "pigmentation", "niacinamide"],
    category: "skin",
    baseScore: 88,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/skin-clarifying/Copy%20of%20For%20%281%29_49zo6l.png?tr=w-600",
    url: "https://bebodywise.com/skin-clarifying",
    rating: 4.7,
    reviewCount: 259,
  },
  {
    id: "acne-spot-correction",
    brand: "Be Bodywise",
    name: "2% Salicylic Acid Gel",
    price: 499,
    mrp: 499,
    concern: ["skin"],
    gender: ["female"],
    segment: ["female-18-25", "female-25-35"],
    followUp: ["acne", "spots", "pimples"],
    category: "skin",
    baseScore: 87,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1648210350/staging/products/acne-spot-correction/0_2SAG/CAROUSEL/0_2.png?tr=w-800",
    url: "https://bebodywise.com/acne-spot-correction",
    rating: 4.5,
    reviewCount: 149,
  },
  {
    id: "2-salicylic-acid-face-wash",
    brand: "Be Bodywise",
    name: "2% Salicylic Acid Face Wash",
    price: 299,
    mrp: 299,
    concern: ["skin"],
    gender: ["female"],
    segment: ["female-18-25", "female-25-35"],
    followUp: ["acne", "oily", "salicylic"],
    category: "skin",
    baseScore: 83,
    image: "https://i.mscwlns.co/media/misc/others/AppThumbnail_SAFW_4uzp3w.jpg?tr=w-600",
    url: "https://bebodywise.com/2-salicylic-acid-face-wash",
    rating: 4.6,
    reviewCount: 71,
  },
  {
    id: "oil-control-moisturiser",
    brand: "Be Bodywise",
    name: "HA Moisturizer for Oily Skin",
    price: 349,
    mrp: 349,
    concern: ["skin"],
    gender: ["female"],
    segment: ["female-18-25", "female-25-35"],
    followUp: ["oily", "acne", "hydration"],
    category: "skin",
    baseScore: 82,
    image: "https://i.mscwlns.co/media/misc/pdp/oil-control-moisturiser/00_1_E0P0E6yUE.png?tr=w-600",
    url: "https://bebodywise.com/oil-control-moisturiser",
    rating: 4.7,
    reviewCount: 45,
  },
  {
    id: "retinol-cream",
    brand: "Be Bodywise",
    name: "Retinol Cream",
    price: 599,
    mrp: 599,
    concern: ["skin"],
    gender: ["female"],
    segment: ["female-25-35", "female-35-plus"],
    followUp: ["dullness", "aging", "pigmentation", "retinol"],
    category: "skin",
    baseScore: 86,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1613663083/staging/products/skin-regenerate-night/New%20Carousel/new_BW_night_cream_pdp.jpg?tr=w-800",
    url: "https://bebodywise.com/retinol-cream",
    rating: 4.6,
    reviewCount: 26,
  },
  {
    id: "collagen-skin-gummies-30n",
    brand: "Be Bodywise",
    name: "Collagen Builder Gummies",
    price: 549,
    mrp: 549,
    concern: ["skin"],
    gender: ["female"],
    segment: ["female-25-35", "female-35-plus"],
    followUp: ["aging", "dullness", "glow", "collagen"],
    category: "skin",
    baseScore: 84,
    image: "https://i.mscwlns.co/media/misc/others/AppThumbnail_Collagen30_a08cuw.jpg?tr=w-600",
    url: "https://bebodywise.com/collagen-skin-gummies-30n",
    rating: 4.4,
    reviewCount: 38,
  },
  {
    id: "1-salicylic-acid-facewash-deal",
    brand: "Be Bodywise",
    name: "1% Salicylic Acid Face Wash (Foam-Based)",
    price: 199,
    mrp: 349,
    concern: ["skin"],
    gender: ["female"],
    segment: ["female-18-25", "female-25-35"],
    followUp: ["acne", "oily"],
    category: "skin",
    baseScore: 80,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/acne-control-wash/1_Product_Hero-1_5zd4hj.jpg?tr=w-600",
    url: "https://bebodywise.com/1-salicylic-acid-facewash-deal",
    rating: 4.5,
    reviewCount: 360,
  },
  {
    id: "4-aha-bha-underarm-roll-on",
    brand: "Be Bodywise",
    name: "4% AHA BHA Underarm Roll On",
    price: 399,
    mrp: 399,
    concern: ["skin"],
    gender: ["female"],
    segment: ["female-18-25", "female-25-35", "female-35-plus"],
    followUp: ["underarm", "body skin", "dark spots"],
    category: "skin",
    baseScore: 75,
    image: "https://i.mscwlns.co/media/misc/others/AppThumbnail_UARO_Flora_a3aoe4.jpg?tr=w-600",
    url: "https://bebodywise.com/4-aha-bha-underarm-roll-on",
    rating: 4.7,
    reviewCount: 62,
  },
  {
    id: "1-salicylic-acid-body-wash",
    brand: "Be Bodywise",
    name: "1% Salicylic Acid Body Wash",
    price: 349,
    mrp: 349,
    concern: ["skin"],
    gender: ["female"],
    segment: ["female-18-25", "female-25-35", "female-35-plus"],
    followUp: ["body skin", "bacne", "body acne"],
    category: "skin",
    baseScore: 74,
    image: "https://i.mscwlns.co/media/misc/others/AppThumbnail_SABW250ml_h38n6e.jpg?tr=w-600",
    url: "https://bebodywise.com/1-salicylic-acid-body-wash",
    rating: 4.7,
    reviewCount: 414,
  },
  {
    id: "5-lactic-acid-body-lotion",
    brand: "Be Bodywise",
    name: "5% Lactic Acid Body Lotion",
    price: 499,
    mrp: 499,
    concern: ["skin"],
    gender: ["female"],
    segment: ["female-18-25", "female-25-35", "female-35-plus"],
    followUp: ["dryness", "body skin", "rough skin"],
    category: "skin",
    baseScore: 73,
    image: "https://i.mscwlns.co/media/misc/others/AppThumbnail_LacticLotion_3huwy8.jpg?tr=w-600",
    url: "https://bebodywise.com/5-lactic-acid-body-lotion",
    rating: 4.5,
    reviewCount: 56,
  },

  // ── WEIGHT ────────────────────────────────────────────────────
  {
    id: "apple-cider-vinegar-effervescent-tablets-pack-4",
    brand: "Be Bodywise",
    name: "Apple Cider Vinegar Effervescent Tablets - Pack of 4",
    price: 999,
    mrp: 1596,
    concern: ["weight"],
    gender: ["female"],
    segment: ["female-18-25", "female-25-35", "female-35-plus"],
    followUp: ["weight loss", "fat", "acv", "metabolism"],
    category: "weight",
    baseScore: 84,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1638857826/staging/products/apple-cider-vinegar-effervescent-tablets/PACK%20OF%204/acv-pack-of-4.png?tr=w-800",
    url: "https://bebodywise.com/apple-cider-vinegar-effervescent-tablets-pack-4",
    rating: 4.8,
    reviewCount: 15,
  },
  {
    id: "vegan-plant-protein-powder-women",
    brand: "Be Bodywise",
    name: "Vegan Plant Protein Powder",
    price: 1599,
    mrp: 1998,
    concern: ["weight"],
    gender: ["female"],
    segment: ["female-18-25", "female-25-35", "female-35-plus"],
    followUp: ["weight loss", "body composition", "protein", "muscle"],
    category: "weight",
    baseScore: 86,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1626765614/staging/products/Protein/1000x750.jpg?tr=w-800",
    url: "https://bebodywise.com/vegan-plant-protein-powder-women",
    rating: 4.7,
    reviewCount: 23,
  },
  {
    id: "multivitamin-gummies-bw",
    brand: "Be Bodywise",
    name: "Multivitamin Gummies",
    price: 799,
    mrp: 799,
    concern: ["weight"],
    gender: ["female"],
    segment: ["female-18-25", "female-25-35", "female-35-plus"],
    followUp: ["nutrition", "energy", "vitamins"],
    category: "nutrition",
    baseScore: 76,
    image: "https://i.mscwlns.co/media/misc/others/AppThumbnail_MVG_grjhio.jpg?tr=w-600",
    url: "https://bebodywise.com/multivitamin-gummies",
    rating: 4.7,
    reviewCount: 12,
  },

  // ── SLEEP ─────────────────────────────────────────────────────
  {
    id: "advanced-magnesium-gummies-30n",
    brand: "Be Bodywise",
    name: "Advanced Magnesium Gummies (30N)",
    price: 599,
    mrp: 599,
    concern: ["sleep"],
    gender: ["female"],
    segment: ["female-18-25", "female-25-35", "female-35-plus"],
    followUp: ["sleep", "stress", "anxiety", "magnesium"],
    category: "sleep",
    baseScore: 86,
    image: "https://i.mscwlns.co/media/misc/others/AppThumbnail_MG30_539nbe.jpg?tr=w-600",
    url: "https://bebodywise.com/advanced-magnesium-gummies-30n",
  },
  {
    id: "magnesium-glycinate-capsules-60",
    brand: "Be Bodywise",
    name: "Magnesium Glycinate Capsules (60N)",
    price: 499,
    mrp: 599,
    concern: ["sleep"],
    gender: ["female"],
    segment: ["female-18-25", "female-25-35", "female-35-plus"],
    followUp: ["sleep", "insomnia", "magnesium", "relax"],
    category: "sleep",
    baseScore: 84,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/magnesium-glycinate-gummies-60n/Mg%20gummies%20thumbnail_4icbpe.jpg?tr=w-600",
    url: "https://bebodywise.com/magnesium-glycinate-capsules-60",
  },
  {
    id: "magnesium-glycinate-gummies-menopause",
    brand: "Be Bodywise",
    name: "Magnesium Gummies for Perimenopause Care",
    price: 899,
    mrp: 999,
    concern: ["sleep"],
    gender: ["female"],
    segment: ["female-35-plus"],
    followUp: ["sleep", "perimenopause", "menopause", "hot flashes"],
    category: "sleep",
    baseScore: 88,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/magnesium-glycinate-gummies-60n/Mg%20gummies%20thumbnail_4icbpe.jpg?tr=w-600",
    url: "https://bebodywise.com/magnesium-glycinate-gummies-menopause",
  },

  // ── ENERGY / GUT ──────────────────────────────────────────────
  {
    id: "vaginal-probiotic-capsules",
    brand: "Be Bodywise",
    name: "Vaginal Health Probiotic Capsules",
    price: 549,
    mrp: 549,
    concern: ["energy"],
    gender: ["female"],
    segment: ["female-18-25", "female-25-35", "female-35-plus"],
    followUp: ["gut", "probiotic", "hormonal", "bloating"],
    category: "energy",
    baseScore: 83,
    image: "https://i.mscwlns.co/media/misc/others/AppThumbnail_VaginalHealthCapsules_379xcg.jpg?tr=w-600",
    url: "https://bebodywise.com/vaginal-probiotic-capsules",
  },
  {
    id: "calcium-gummies-bw",
    brand: "Be Bodywise",
    name: "Calcium Gummies",
    price: 549,
    mrp: 549,
    concern: ["energy"],
    gender: ["female"],
    segment: ["female-18-25", "female-25-35", "female-35-plus"],
    followUp: ["bone health", "calcium", "nutrition", "fatigue"],
    category: "nutrition",
    baseScore: 80,
    image: "https://i.mscwlns.co/media/misc/others/AppThumbnail_CalG30_3zyiku.jpg?tr=w-600",
    url: "https://bebodywise.com/calcium-gummies",
  },

  // ── HORMONAL / PERIOD ─────────────────────────────────────────
  {
    id: "magnesium-glycinate-gummies-60n-xp2",
    brand: "Be Bodywise",
    name: "Magnesium Glycinate Gummies (60N)",
    price: 899,
    mrp: 999,
    concern: ["hormones"],
    gender: ["female"],
    segment: ["female-18-25", "female-25-35", "female-35-plus"],
    followUp: ["pms", "hormonal", "period", "cramps", "mood"],
    category: "hormones",
    baseScore: 86,
    image: "https://i.mscwlns.co/media/misc/others/AppThumbnail_MgGummies60N_bbpixy.jpg?tr=w-600",
    url: "https://bebodywise.com/magnesium-glycinate-gummies-60n-xp2",
  },
  {
    id: "advanced-magnesium-gummies-60n",
    brand: "Be Bodywise",
    name: "Advanced Magnesium Gummies (60N)",
    price: 1099,
    mrp: 1199,
    concern: ["hormones"],
    gender: ["female"],
    segment: ["female-25-35", "female-35-plus"],
    followUp: ["pms", "hormonal", "perimenopause", "cramps", "period"],
    category: "hormones",
    baseScore: 87,
    image: "https://i.mscwlns.co/media/misc/others/AppThumbnail_MgGummies60N_bbpixy.jpg?tr=w-600",
    url: "https://bebodywise.com/advanced-magnesium-gummies-60n",
  },
  {
    id: "skin-health-gummies-hormones",
    brand: "Be Bodywise",
    name: "Skin Health Gummies (30)",
    price: 499,
    mrp: 599,
    concern: ["hormones"],
    gender: ["female"],
    segment: ["female-18-25", "female-25-35"],
    followUp: ["hormonal acne", "acne mood", "skin"],
    category: "skin",
    baseScore: 80,
    image: "https://i.mscwlns.co/media/misc/others/AppThumbnail_Collagen30_a08cuw.jpg?tr=w-600",
    url: "https://bebodywise.com/skin-health-gummies",
    rating: 4.4,
    reviewCount: 38,
  },
  {
    id: "multivitamin-gummies-hormones",
    brand: "Be Bodywise",
    name: "Multivitamin Gummies",
    price: 799,
    mrp: 799,
    concern: ["hormones"],
    gender: ["female"],
    segment: ["female-18-25", "female-25-35", "female-35-plus"],
    followUp: ["low energy", "nutrition", "vitamins", "fatigue"],
    category: "nutrition",
    baseScore: 77,
    image: "https://i.mscwlns.co/media/misc/others/AppThumbnail_MVG_grjhio.jpg?tr=w-600",
    url: "https://bebodywise.com/multivitamin-gummies",
    rating: 4.7,
    reviewCount: 12,
  },
];
