import type { Product } from "@/lib/protocolEngine";

/* ──────────────────────────────────────────────────────────────
   Little Joys — Mom products only (no kids catalog)
   These surface for female users who are postpartum/breastfeeding.
   baseScore is intentionally low so they only appear when
   the postpartum followUp string boosts their score above 70.
   ────────────────────────────────────────────────────────────── */

export const LJ_MOM_PRODUCTS: Product[] = [
  {
    id: "lj-multivitamin-gummies-mothers",
    brand: "Little Joys",
    name: "Multivitamin Gummies for Mothers (30N)",
    price: 549,
    mrp: 549,
    concern: ["energy"],
    gender: ["female"],
    segment: ["female-25-35", "female-35-plus"],
    followUp: ["postpartum", "breastfeeding", "nutrition", "energy"],
    category: "nutrition",
    baseScore: 62,
    image: "https://i.mscwlns.co/media/misc/pdp/multivitamin-gummies-mothers/Thumbnail%20Images%20Mom%20MVG_282xiv.png?tr=w-600",
    url: "https://littlejoys.co/multivitamin-gummies-mothers",
  },
  {
    id: "lj-calcium-gummies-moms",
    brand: "Little Joys",
    name: "Calcium Gummies for Moms",
    price: 549,
    mrp: 549,
    concern: ["energy"],
    gender: ["female"],
    segment: ["female-25-35", "female-35-plus"],
    followUp: ["postpartum", "breastfeeding", "calcium", "bone health"],
    category: "nutrition",
    baseScore: 61,
    image: "https://i.mscwlns.co/media/misc/pdp/calcium-gummies-moms/Thumbnail%20Images%20Calcium_49gd2x.png?tr=w-600",
    url: "https://littlejoys.co/calcium-gummies-moms",
  },
  {
    id: "lj-magnesium-gummies-moms",
    brand: "Little Joys",
    name: "Magnesium Gummies for Moms (30N)",
    price: 649,
    mrp: 649,
    concern: ["sleep"],
    gender: ["female"],
    segment: ["female-25-35", "female-35-plus"],
    followUp: ["postpartum", "breastfeeding", "sleep", "stress"],
    category: "sleep",
    baseScore: 60,
    image: "https://i.mscwlns.co/media/misc/pdp/magnesium-gummies-moms-bb/magnesium%2030N%20thumbnail_8xpdpv.jpg?tr=w-600",
    url: "https://littlejoys.co/magnesium-gummies-moms-bb",
  },
  {
    id: "lj-biotin-hair-gummies-moms",
    brand: "Little Joys",
    name: "Biotin Hair Gummies for Moms",
    price: 499,
    mrp: 549,
    concern: ["hair"],
    gender: ["female"],
    segment: ["female-25-35", "female-35-plus"],
    followUp: ["postpartum", "breastfeeding", "hair fall"],
    category: "hair",
    baseScore: 62,
    image: "https://i.mscwlns.co/media/misc/pdp/hair-health-gummies-moms/Thumbnail%20Images%20Biotin_2g6fj6.png?tr=w-600",
    url: "https://littlejoys.co/hair-health-gummies-moms",
  },
  {
    id: "lj-nutrimix-moms",
    brand: "Little Joys",
    name: "Nutrimix for Moms (400g)",
    price: 599,
    mrp: 599,
    concern: ["energy"],
    gender: ["female"],
    segment: ["female-25-35", "female-35-plus"],
    followUp: ["postpartum", "breastfeeding", "nutrition", "energy", "recovery"],
    category: "nutrition",
    baseScore: 63,
    image: "https://i.mscwlns.co/media/misc/pdp/mamamix-nutrition-powder/thumbnail_3xxd8i.png?tr=w-600",
    url: "https://littlejoys.co/mamamix-nutrition-powder",
  },
];
