import type { Product } from "@/lib/protocolEngine";

// Little Joys kids & moms catalog.
// These surface on the /explore page for child profiles (filtered by brand === "Little Joys").
// concern/segment/gender values are set but the kids explore view primarily sorts by baseScore.
export const LJ_PRODUCTS: Product[] = [

  // ── Gummies ──────────────────────────────────────────────────────────────────

  {
    id: "multivitamin-gummies",
    brand: "Little Joys",
    name: "Multivitamin Gummies 2+ (30N)",
    price: 499, mrp: 499,
    concern: ["energy"], gender: ["all"],
    segment: ["kids-2-5", "kids-6-12"],
    followUp: ["nutrition", "vitamins", "immunity"],
    category: "gummies", baseScore: 90,
    image: "https://i.mscwlns.co/media/misc/others/Multivitamin%20Gummies%202%2B%20%2830%20Days%20Pack%29_lwfoq5.jpg?tr=w-600",
    url: "https://ourlittlejoys.com/products/multivitamin-gummies",
  },
  {
    id: "multivitamin-gummies-7plus-30",
    brand: "Little Joys",
    name: "Multivitamin Gummies 7+ (30N)",
    price: 499, mrp: 549,
    concern: ["energy"], gender: ["all"],
    segment: ["kids-6-12", "kids-13-plus"],
    followUp: ["nutrition", "vitamins", "immunity"],
    category: "gummies", baseScore: 90,
    image: "https://i.mscwlns.co/media/misc/pdp/multivitamin-gummies-7/MVG7%2B_WBG_9y4hy9.jpg?tr=w-600",
    url: "https://ourlittlejoys.com/products/multivitamin-gummies-7plus-30",
  },
  {
    id: "multivitamin-gummies-13-18",
    brand: "Little Joys",
    name: "Multivitamin Gummies 13+ (30N)",
    price: 499, mrp: 549,
    concern: ["energy"], gender: ["all"],
    segment: ["kids-13-plus"],
    followUp: ["nutrition", "vitamins", "immunity", "teen"],
    category: "gummies", baseScore: 89,
    image: "https://i.mscwlns.co/media/misc/pdp/multivitamin-gummies-13-18/Thumbnail_2_f6gx6f.jpg?tr=w-600",
    url: "https://ourlittlejoys.com/products/multivitamin-gummies-13-18",
  },
  {
    id: "brain-booster-gummies",
    brand: "Little Joys",
    name: "Brain Health Gummies 2+ (30N)",
    price: 499, mrp: 549,
    concern: ["energy"], gender: ["all"],
    segment: ["kids-2-5", "kids-6-12"],
    followUp: ["brain", "dha", "omega3", "focus", "learning"],
    category: "gummies", baseScore: 88,
    image: "https://i.mscwlns.co/media/misc/others/DHA%20Omega3%20Brain%20Gummies%202%2B%20%2830N%29_47ta0n.jpg?tr=w-600",
    url: "https://ourlittlejoys.com/products/brain-booster-gummies",
  },
  {
    id: "brain-gummies-7-packof60",
    brand: "Little Joys",
    name: "Brain Health Gummies 7+ (60N)",
    price: 849, mrp: 1049,
    concern: ["energy"], gender: ["all"],
    segment: ["kids-6-12", "kids-13-plus"],
    followUp: ["brain", "dha", "omega3", "focus", "learning"],
    category: "gummies", baseScore: 87,
    image: "https://i.mscwlns.co/media/misc/pdp/brain-gummies-7-packof60/brain-gummies-7-packof60_ld8bii.jpg?tr=w-600",
    url: "https://ourlittlejoys.com/products/brain-gummies-7-packof60",
  },
  {
    id: "calcium-gummies",
    brand: "Little Joys",
    name: "Calcium Gummies (30N)",
    price: 499, mrp: 549,
    concern: ["energy"], gender: ["all"],
    segment: ["kids-2-5", "kids-6-12", "kids-13-plus"],
    followUp: ["calcium", "bone", "growth", "teeth"],
    category: "gummies", baseScore: 86,
    image: "https://i.mscwlns.co/media/misc/others/Calcium%20Gummies%20Mango%20%2830N%29_cv3gye.jpg?tr=w-600",
    url: "https://ourlittlejoys.com/products/calcium-gummies",
  },
  {
    id: "magnesium-gummies-30-2",
    brand: "Little Joys",
    name: "Magnesium Gummies 4+ (30N)",
    price: 499, mrp: 549,
    concern: ["sleep"], gender: ["all"],
    segment: ["kids-2-5", "kids-6-12"],
    followUp: ["sleep", "calm", "magnesium", "relaxation"],
    category: "gummies", baseScore: 84,
    image: "https://i.mscwlns.co/media/misc/pdp/magnesium-gummies-30/Website-Thumbnail%20%281%29_fk6xic.jpg?tr=w-600",
    url: "https://ourlittlejoys.com/products/magnesium-gummies-30-2",
  },
  {
    id: "magnesium-gummies-30-7",
    brand: "Little Joys",
    name: "Magnesium Gummies 13+ (30N)",
    price: 499, mrp: 549,
    concern: ["sleep"], gender: ["all"],
    segment: ["kids-13-plus"],
    followUp: ["sleep", "calm", "magnesium", "stress", "teen"],
    category: "gummies", baseScore: 84,
    image: "https://i.mscwlns.co/media/misc/pdp/magnesium-gummies-30/Website-Thumbnail%20%281%29_fk6xic.jpg?tr=w-600",
    url: "https://ourlittlejoys.com/products/magnesium-gummies-30-7",
  },
  {
    id: "hair-gummies",
    brand: "Little Joys",
    name: "Biotin Hair Gummies (30N)",
    price: 499, mrp: 499,
    concern: ["hair"], gender: ["all"],
    segment: ["kids-13-plus"],
    followUp: ["hair", "biotin", "hair fall", "teen"],
    category: "gummies", baseScore: 82,
    image: "https://i.mscwlns.co/media/misc/pdp/hair-gummies/Hair-gummies_1000X750___1__Tx5NnxxbzN.jpg?tr=w-600",
    url: "https://ourlittlejoys.com/products/hair-gummies",
  },

  // ── Nutrition Powders ────────────────────────────────────────────────────────

  {
    id: "nutrimix-nutrition-powder-min",
    brand: "Little Joys",
    name: "NutriMix Chocolate 2+ (350g)",
    price: 599, mrp: 699,
    concern: ["energy"], gender: ["all"],
    segment: ["kids-2-5", "kids-6-12"],
    followUp: ["nutrition", "protein", "growth", "milk"],
    category: "nutrition", baseScore: 85,
    image: "https://i.mscwlns.co/media/misc/pdp/nutrimix-nutrition-powder/Nutrimiz_WBG_5gjc5h.jpg?tr=w-600",
    url: "https://ourlittlejoys.com/products/nutrimix-nutrition-powder-min",
  },
  {
    id: "nutrimix-nutrition-powder-vanilla",
    brand: "Little Joys",
    name: "NutriMix Vanilla 2+ (350g)",
    price: 649, mrp: 699,
    concern: ["energy"], gender: ["all"],
    segment: ["kids-2-5", "kids-6-12"],
    followUp: ["nutrition", "protein", "growth", "milk"],
    category: "nutrition", baseScore: 83,
    image: "https://i.mscwlns.co/media/misc/others/Nutrimix%20Vanilla%20Nutrition%20Powder%202%2B%20%28350g%29_e90omx.jpg?tr=w-600",
    url: "https://ourlittlejoys.com/products/nutrimix-nutrition-powder-vanilla",
  },
  {
    id: "nutrimix-nutrition-powder-strawberry",
    brand: "Little Joys",
    name: "NutriMix Strawberry (350g)",
    price: 699, mrp: 699,
    concern: ["energy"], gender: ["all"],
    segment: ["kids-2-5", "kids-6-12"],
    followUp: ["nutrition", "protein", "growth", "milk"],
    category: "nutrition", baseScore: 82,
    image: "https://i.mscwlns.co/media/misc/others/Nutrimix%20Strawberry%20Nutrition%20Powder_3yhb0p.jpg?tr=w-600",
    url: "https://ourlittlejoys.com/products/nutrimix-nutrition-powder-strawberry",
  },
  {
    id: "nutrimix-nutrition-powder-7",
    brand: "Little Joys",
    name: "NutriMix 7+ Chocolate (300g)",
    price: 649, mrp: 649,
    concern: ["energy"], gender: ["all"],
    segment: ["kids-6-12", "kids-13-plus"],
    followUp: ["nutrition", "protein", "growth", "school"],
    category: "nutrition", baseScore: 83,
    image: "https://i.mscwlns.co/media/misc/others/Nutrimix%207%2B%20Chocolate%20Nutrition%20Powder_11lndz.jpg?tr=w-600",
    url: "https://ourlittlejoys.com/products/nutrimix-nutrition-powder-7",
  },

  // ── Personal Care ────────────────────────────────────────────────────────────

  {
    id: "neem-bodywash-new",
    brand: "Little Joys",
    name: "Neem Bodywash (250ml)",
    price: 249, mrp: 349,
    concern: ["skin"], gender: ["all"],
    segment: ["kids-2-5", "kids-6-12", "kids-13-plus"],
    followUp: ["skin", "bodywash", "neem", "natural"],
    category: "personal-care", baseScore: 75,
    image: "https://i.mscwlns.co/media/misc/others/Neem%20Bodywash_g4k2xe.jpg?tr=w-600",
    url: "https://ourlittlejoys.com/products/neem-bodywash-new",
  },
  {
    id: "aloe-shampoo-new",
    brand: "Little Joys",
    name: "Aloe Vera Shampoo (200ml)",
    price: 324, mrp: 399,
    concern: ["hair"], gender: ["all"],
    segment: ["kids-2-5", "kids-6-12", "kids-13-plus"],
    followUp: ["hair", "shampoo", "aloe", "gentle"],
    category: "personal-care", baseScore: 74,
    image: "https://i.mscwlns.co/media/misc/others/Aloe%20Vera%20Shampoo%20%28250ml%29_jyp0ok.jpg?tr=w-600",
    url: "https://ourlittlejoys.com/products/aloe-shampoo-new",
  },
  {
    id: "amla-shampoo",
    brand: "Little Joys",
    name: "Amla Shampoo (250ml)",
    price: 399, mrp: 399,
    concern: ["hair"], gender: ["all"],
    segment: ["kids-6-12", "kids-13-plus"],
    followUp: ["hair", "shampoo", "amla", "natural"],
    category: "personal-care", baseScore: 73,
    image: "https://i.mscwlns.co/media/misc/pdp/amla-shampoo/2901_CR__1__BGa9EDsCC.jpg?tr=w-600",
    url: "https://ourlittlejoys.com/products/amla-shampoo",
  },
  {
    id: "multivitamin-toothpaste",
    brand: "Little Joys",
    name: "Multivitamin Toothpaste (80g)",
    price: 199, mrp: 199,
    concern: ["energy"], gender: ["all"],
    segment: ["kids-6-12", "kids-13-plus"],
    followUp: ["teeth", "oral", "toothpaste", "fluoride"],
    category: "personal-care", baseScore: 72,
    image: "https://i.mscwlns.co/media/misc/others/Multivitamin%20Toothpaste%205%2B_eefdgc.jpg?tr=w-600",
    url: "https://ourlittlejoys.com/products/multivitamin-toothpaste",
  },
  {
    id: "peppa-body-lotion-for-kids",
    brand: "Little Joys",
    name: "Moisturizing Body Lotion (200ml)",
    price: 349, mrp: 349,
    concern: ["skin"], gender: ["all"],
    segment: ["kids-2-5", "kids-6-12"],
    followUp: ["skin", "lotion", "moisturiser", "dry skin"],
    category: "personal-care", baseScore: 71,
    image: "https://i.mscwlns.co/media/misc/pdp/peppa-body-lotion-for-kids/2850%20Cr%206_5jxs82.jpg?tr=w-800",
    url: "https://ourlittlejoys.com/products/peppa-body-lotion-for-kids",
  },

  // ── Healthy Snacks ───────────────────────────────────────────────────────────

  {
    id: "millet-chocos",
    brand: "Little Joys",
    name: "Millet Choco Crunch (250g)",
    price: 299, mrp: 299,
    concern: ["energy"], gender: ["all"],
    segment: ["kids-2-5", "kids-6-12"],
    followUp: ["snack", "millet", "healthy snack"],
    category: "healthysnacks", baseScore: 70,
    image: "https://i.mscwlns.co/media/misc/pdp/millet-chocos/Millet%20Chocos_j0d2yj.jpg?tr=w-600",
    url: "https://ourlittlejoys.com/products/millet-chocos",
  },
  {
    id: "chocolate-spread",
    brand: "Little Joys",
    name: "Healthy Chocolate Spread (300g)",
    price: 449, mrp: 499,
    concern: ["energy"], gender: ["all"],
    segment: ["kids-2-5", "kids-6-12", "kids-13-plus"],
    followUp: ["snack", "spread", "chocolate", "healthy"],
    category: "healthysnacks", baseScore: 69,
    image: "https://i.mscwlns.co/media/misc/others/Chocolate%20Hazelnut%20Spread%20%28300g%29_c2dcg7.jpg?tr=w-600",
    url: "https://ourlittlejoys.com/products/chocolate-spread",
  },
  {
    id: "peanut-butter-chocolate",
    brand: "Little Joys",
    name: "Chocolate Peanut Butter (500g)",
    price: 399, mrp: 399,
    concern: ["energy"], gender: ["all"],
    segment: ["kids-6-12", "kids-13-plus"],
    followUp: ["snack", "peanut butter", "protein", "healthy"],
    category: "healthysnacks", baseScore: 68,
    image: "https://i.mscwlns.co/media/misc/others/Chocolate%20Peanut%20Butter%20-%20500%20g_ao9euh.jpg?tr=w-600",
    url: "https://ourlittlejoys.com/products/peanut-butter-chocolate",
  },
  {
    id: "millet-pancake",
    brand: "Little Joys",
    name: "Millet Pancake Mix",
    price: 199, mrp: 199,
    concern: ["energy"], gender: ["all"],
    segment: ["kids-2-5", "kids-6-12"],
    followUp: ["snack", "millet", "breakfast", "healthy"],
    category: "healthysnacks", baseScore: 67,
    image: "https://i.mscwlns.co/media/misc/pdp/millet-pancake/Slide%201.1_2v686j.jpg?tr=w-600",
    url: "https://ourlittlejoys.com/products/millet-pancake",
  },
  {
    id: "fruit-jam",
    brand: "Little Joys",
    name: "Strawberry Honey Jam",
    price: 249, mrp: 249,
    concern: ["energy"], gender: ["all"],
    segment: ["kids-2-5", "kids-6-12", "kids-13-plus"],
    followUp: ["snack", "jam", "no sugar", "natural"],
    category: "healthysnacks", baseScore: 66,
    image: "https://i.mscwlns.co/media/misc/pdp/jam-glass/Strawberry%20Honey%20Jam%20Glass%20Jar%20copy_2v2sy1.jpg?tr=w-600",
    url: "https://ourlittlejoys.com/products/fruit-jam",
  },
];
