import type { Product } from "@/lib/protocolEngine";

/* ══════════════════════════════════════════════════════════════
   Man Matters product catalog — cleaned from MM API data.
   50 OTC products across hair, beard, skin, weight,
   nutrition (energy/gut), performance (hormones), sleep.
   No Rx, no kits, no duplicates, no junk.
   ══════════════════════════════════════════════════════════════ */

export const MM_PRODUCTS: Product[] = [
  // ── BEARD ──
  {
    id: "beard-gummies",
    brand: "Man Matters",
    name: "Beard Gummies for Less Dense beard",
    price: 449,
    mrp: 499,
    concern: ["beard"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["patchy beard", "slow growth"],
    category: "beard",
    baseScore: 85,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/2024336/Beard%20Gummies_bbgj46.png?tr=w-600",
    url: "https://manmatters.com/beard-gummies",
    rating: 4.6,
    reviewCount: 69,
  },
  {
    id: "minoxbeard",
    brand: "Man Matters",
    name: "Man Matters BeardGro Serum with Anagain",
    price: 549,
    mrp: 599,
    concern: ["beard"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["patchy beard", "slow growth"],
    category: "beard",
    baseScore: 80,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/2024153/Creative-1_dgq3vo.jpg?tr=w-600",
    url: "https://manmatters.com/minoxbeard",
  },
  {
    id: "beard-tonic",
    brand: "Man Matters",
    name: "BeardGro Tonic (2 Month Pack)",
    price: 699,
    mrp: 998,
    concern: ["beard"],
    gender: ["male"],
    segment: ["male-18-25"],
    followUp: ["general health"],
    category: "beard",
    baseScore: 86,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/26166855/Untitled__1600___1200_px___3__LdTc3FrV6.png?tr=w-600",
    url: "https://manmatters.com/beard-tonic",
    rating: 4.8,
    reviewCount: 23,
  },
  // ── HAIR ──
  {
    id: "dermaroller",
    brand: "Man Matters",
    name: "Derma Roller for Hair 1 mm",
    price: 299,
    mrp: 699,
    concern: ["hair"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35"],
    followUp: ["hair fall", "thinning"],
    category: "hair",
    baseScore: 80,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/2023223/Old%20Derma%20roller%20%281%29_glsbdw.png?tr=w-600",
    url: "https://manmatters.com/dermaroller",
  },
  {
    id: "ketoconazole-shampoo",
    brand: "Man Matters",
    name: "1% Ketoconazole Shampoo 100 ml",
    price: 299,
    mrp: 299,
    concern: ["hair"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["dandruff"],
    category: "hair",
    baseScore: 80,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/1144207/ADS%20100%20%282%29_c8hoq7.png?tr=w-600",
    url: "https://manmatters.com/ketoconazole-shampoo",
    rating: 4.3,
    reviewCount: 48,
  },
  {
    id: "Ketoconazole",
    brand: "Man Matters",
    name: "Anti-Dandruff Shampoo (100 ml)",
    price: 299,
    mrp: 299,
    concern: ["hair"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["dandruff"],
    category: "hair",
    baseScore: 80,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/1144207/ADS_1b2kg6.png?tr=w-600",
    url: "https://manmatters.com/Ketoconazole",
    rating: 4.3,
    reviewCount: 48,
  },
  {
    id: "massager",
    brand: "Man Matters",
    name: "Scalp Massager (1N)",
    price: 299,
    mrp: 499,
    concern: ["hair"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35"],
    followUp: ["hair fall", "thinning"],
    category: "hair",
    baseScore: 80,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/17036119/Scalp%20Massager_c7amwz.png?tr=w-600",
    url: "https://manmatters.com/massager",
    rating: 3.6,
    reviewCount: 74,
  },
  {
    id: "hair-oil",
    brand: "Man Matters",
    name: "Hair Growth Oil (100ml)",
    price: 315,
    mrp: 349,
    concern: ["hair"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35"],
    followUp: ["hair fall", "thinning"],
    category: "hair",
    baseScore: 80,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/1601/Hair%20oil_kg5vgl.png?tr=w-600",
    url: "https://manmatters.com/hair-oil",
    rating: 4.2,
    reviewCount: 67,
  },
  {
    id: "ketoconazole-lotion",
    brand: "Man Matters",
    name: "Ketopower+ Lotion",
    price: 349,
    mrp: 349,
    concern: ["hair"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["hair fall", "thinning", "dandruff"],
    category: "hair",
    baseScore: 86,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/3526713/ketopower%2B%20lotion_47u08q.jpg?tr=w-600",
    url: "https://manmatters.com/ketoconazole-lotion",
    rating: 4.8,
    reviewCount: 5,
  },
  {
    id: "deep-nourishment-hair-mask",
    brand: "Man Matters",
    name: "Deep Nourishment Hair Mask",
    price: 349,
    mrp: 349,
    concern: ["hair"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["general health"],
    category: "hair",
    baseScore: 80,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1626788157/Hair%20mask/Hair-mask-_1600X1200.jpg?tr=w-800",
    url: "https://manmatters.com/deep-nourishment-hair-mask",
  },
  {
    id: "adl",
    brand: "Man Matters",
    name: "Dandruff Removal Lotion",
    price: 379,
    mrp: 399,
    concern: ["hair"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["dandruff"],
    category: "hair",
    baseScore: 80,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/5100216/Dandruff%20removal%20lotion_415fve.jpg?tr=w-600",
    url: "https://manmatters.com/adl",
    rating: 4.3,
    reviewCount: 35,
  },
  {
    id: "nourish-hair-tablets",
    brand: "Man Matters",
    name: "NOURISH Hair Tablets",
    price: 399,
    mrp: 399,
    concern: ["hair"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["general health"],
    category: "hair",
    baseScore: 80,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1604745554/Man%20Matters/Card%20image%20change/Hair/Nourish%20Tabs/GROW-Hair-Tablets_1600X1200.jpg?tr=w-800",
    url: "https://manmatters.com/nourish-hair-tablets",
    rating: 4.4,
    reviewCount: 81,
  },
  {
    id: "ahs",
    brand: "Man Matters",
    name: "Anti Hair Fall Shampoo for Menn",
    price: 399,
    mrp: 399,
    concern: ["hair"],
    gender: ["male"],
    segment: ["male-25-35"],
    followUp: ["hair fall", "thinning", "dandruff"],
    category: "hair",
    baseScore: 80,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1604745272/Man%20Matters/Card%20image%20change/Hair/Anti%20hairfall%20shampoo/Anti-Hairfall-Shampoo_1600X1200.jpg?tr=w-800",
    url: "https://manmatters.com/ahs",
  },
  {
    id: "hair-gummies",
    brand: "Man Matters",
    name: "Biotin Hair Gummies Regular (60N)",
    price: 424,
    mrp: 849,
    concern: ["hair"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35"],
    followUp: ["hair fall", "thinning"],
    category: "hair",
    baseScore: 85,
    image: "https://i.mscwlns.co/media/misc/others/Hair%20gummies_1ch4cw.png?tr=w-600",
    url: "https://manmatters.com/hair-gummies",
    rating: 4.4,
    reviewCount: 248,
  },
  {
    id: "hair-strength-serum",
    brand: "Man Matters",
    name: "Hair Strengthening Serum 60ml",
    price: 499,
    mrp: 499,
    concern: ["hair"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35"],
    followUp: ["hair fall", "thinning"],
    category: "hair",
    baseScore: 80,
    image: "https://i.mscwlns.co/media/misc/others/thumb_ctvc8p.png?tr=w-600",
    url: "https://manmatters.com/hair-strength-serum",
    rating: 4.3,
    reviewCount: 26,
  },
  {
    id: "advance-ads",
    brand: "Man Matters",
    name: "Advance Daily Use Anti-Dandruff Shampoo",
    price: 499,
    mrp: 549,
    concern: ["hair"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["dandruff"],
    category: "hair",
    baseScore: 80,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/2025050/ADUS_3n9h9m.png?tr=w-600",
    url: "https://manmatters.com/advance-ads",
  },
  {
    id: "advanced-hair-oil",
    brand: "Man Matters",
    name: "Advanced Hair Oil",
    price: 499,
    mrp: 549,
    concern: ["hair"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["hair fall", "thinning"],
    category: "hair",
    baseScore: 84,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1635321873/Man%20Matters/Advanced%20Hair%20Oil/Product%20images/Advanced-Hair-Oil_1600X1200.jpg?tr=w-800",
    url: "https://manmatters.com/advanced-hair-oil",
    rating: 4.7,
    reviewCount: 15,
  },
  {
    id: "ads",
    brand: "Man Matters",
    name: "Anti Dandruff Daily Use Shampoo",
    price: 499,
    mrp: 499,
    concern: ["hair"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["dandruff"],
    category: "hair",
    baseScore: 80,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/26166757/Daily%20Use%20ADS_79x04y.jpg?tr=w-600",
    url: "https://manmatters.com/ads",
    rating: 4.3,
    reviewCount: 48,
  },
  {
    id: "Redensyl",
    brand: "Man Matters",
    name: "Redensyl Grow Hair Tonic",
    price: 649,
    mrp: 699,
    concern: ["hair"],
    gender: ["male"],
    segment: ["male-18-25"],
    followUp: ["hair fall", "thinning"],
    category: "hair",
    baseScore: 80,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1604745649/Man%20Matters/Card%20image%20change/Hair/Tonic/Grow-Hair-Tonic_1600X1200.jpg?tr=w-800",
    url: "https://manmatters.com/Redensyl",
    rating: 3.8,
    reviewCount: 128,
  },
  {
    id: "ahs-serum",
    brand: "Man Matters",
    name: "Advanced Hair Regrowth Serum",
    price: 649,
    mrp: 899,
    concern: ["hair"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35"],
    followUp: ["hair fall", "thinning"],
    category: "hair",
    baseScore: 80,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/26166956/Hair-gwoth-serum-_e46sb2.png?tr=w-600",
    url: "https://manmatters.com/ahs-serum",
  },
  // ── NUTRITION ──
  {
    id: "nobloat",
    brand: "Man Matters",
    name: "NoBloat Gut health Blend",
    price: 299,
    mrp: 399,
    concern: ["energy"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["general health"],
    category: "nutrition",
    baseScore: 80,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/2023036/Gut%20health%20%20%281%29_ayvk55.png?tr=w-600",
    url: "https://manmatters.com/nobloat",
  },
  {
    id: "creatine-powder",
    brand: "Man Matters",
    name: "Micronised Creatine Monohydrate - Lime Flavour",
    price: 549,
    mrp: 849,
    concern: ["energy"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["build muscle", "gym"],
    category: "nutrition",
    baseScore: 80,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/2025071/Creatine%20Powder%20Lemon%20125gm_5bjt7h.png?tr=w-600",
    url: "https://manmatters.com/creatine-powder",
  },
  {
    id: "multi-gummies",
    brand: "Man Matters",
    name: "Multivitamin Gummies",
    price: 549,
    mrp: 599,
    concern: ["energy"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["general health"],
    category: "nutrition",
    baseScore: 84,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/13410495/Multivitamin%20Gummies%20%281%29_fki1eo.png?tr=w-600",
    url: "https://manmatters.com/multi-gummies",
    rating: 4.7,
    reviewCount: 20,
  },
  {
    id: "ashwagandha-gummies",
    brand: "Man Matters",
    name: "Ashwagandha Gummies",
    price: 629,
    mrp: 699,
    concern: ["energy"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["general health"],
    category: "nutrition",
    baseScore: 80,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/13222757/Ashwa%20Gummies%20%281%29_jjrtro.png?tr=w-600",
    url: "https://manmatters.com/ashwagandha-gummies",
    rating: 4.4,
    reviewCount: 35,
  },
  {
    id: "creatine-gummies",
    brand: "Man Matters",
    name: "Creatine Gummies",
    price: 799,
    mrp: 799,
    concern: ["energy"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["low energy", "hormonal issues", "build muscle", "gym"],
    category: "nutrition",
    baseScore: 80,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/2025041/Creatine%20Gummies%20pouch_fn65ct.png?tr=w-600",
    url: "https://manmatters.com/creatine-gummies",
  },
  {
    id: "magnesium-gummies",
    brand: "Man Matters",
    name: "Magnesium Glycinate Gummies 60N",
    price: 899,
    mrp: 999,
    concern: ["energy"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["general health"],
    category: "nutrition",
    baseScore: 80,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/2024494/Magnesium%20Gummies_br8d83.jpg?tr=w-600",
    url: "https://manmatters.com/magnesium-gummies",
  },
  {
    id: "whey-protein",
    brand: "Man Matters",
    name: "Whey Protein",
    price: 999,
    mrp: 1499,
    concern: ["energy"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["general health"],
    category: "nutrition",
    baseScore: 90,
    image: "https://i.mscwlns.co/media/misc/pdp/26166740/Whey-Protein-Powder_600X600__mB6ULq4bQ.png?tr=w-600",
    url: "https://manmatters.com/whey-protein",
  },
  {
    id: "plant-protein",
    brand: "Man Matters",
    name: "Plant Protein Powder (500 gm)",
    price: 1299,
    mrp: 1599,
    concern: ["energy"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["build muscle", "gym"],
    category: "nutrition",
    baseScore: 82,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/6923914/Vegain_da99sw.jpg?tr=w-600",
    url: "https://manmatters.com/plant-protein",
    rating: 4.6,
    reviewCount: 202,
  },
  {
    id: "superblend",
    brand: "Man Matters",
    name: "Super Blend - Unflavoured Base (500g)",
    price: 1499,
    mrp: 1499,
    concern: ["energy"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["general health"],
    category: "nutrition",
    baseScore: 80,
    image: "https://i.mscwlns.co/media/misc/others/Super%20Blend%20Pouch-min_em4qks.png?tr=w-600",
    url: "https://manmatters.com/superblend",
  },
  // ── PERFORMANCE ──
  {
    id: "perform-energy-booster-10-effervescent-tablets",
    brand: "Man Matters",
    name: "PERFORM Energy Booster | 10 Effervescent Tablets",
    price: 333,
    mrp: 333,
    concern: ["hormones", "energy"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["general health"],
    category: "performance",
    baseScore: 90,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1622962661/Man%20Matters/Performance%20clean%20up/eff/Effervescent-tablets---10-tabs_1600X1200.jpg?tr=w-800",
    url: "https://manmatters.com/perform-energy-booster-10-effervescent-tablets",
  },
  {
    id: "endure-spray",
    brand: "Man Matters",
    name: "Endure Long Last Spray (20ml)",
    price: 349,
    mrp: 399,
    concern: ["hormones", "energy"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["general health"],
    category: "performance",
    baseScore: 80,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/1626/Endure%20long%20last%20spray%20_e4n97h.png?tr=w-600",
    url: "https://manmatters.com/endure-spray",
    rating: 4.1,
    reviewCount: 273,
  },
  {
    id: "shilajit-gummies",
    brand: "Man Matters",
    name: "Shilajit Gummies 30N",
    price: 499,
    mrp: 499,
    concern: ["hormones", "energy"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["build muscle", "gym"],
    category: "performance",
    baseScore: 80,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/2024331/Option_e2xtu6.png?tr=w-600",
    url: "https://manmatters.com/shilajit-gummies",
  },
  {
    id: "tostero",
    brand: "Man Matters",
    name: "TOSTERO Tablets",
    price: 599,
    mrp: 899,
    concern: ["hormones", "energy"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["general health"],
    category: "performance",
    baseScore: 80,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1622792157/Man%20Matters/Performance%20clean%20up/Tostero/Tostero/Tostero-Capsule_1600X1200.jpg?tr=w-800",
    url: "https://manmatters.com/tostero",
  },
  {
    id: "perform-energy-booster-30-effervescent-tablets",
    brand: "Man Matters",
    name: "PERFORM Energy Booster | 30 Effervescent Tablets",
    price: 799,
    mrp: 999,
    concern: ["hormones", "energy"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["general health"],
    category: "performance",
    baseScore: 84,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1624512500/Man%20Matters/Performance%20clean%20up/effervescent-tablet-1M-_1600X1200.jpg?tr=w-800",
    url: "https://manmatters.com/perform-energy-booster-30-effervescent-tablets",
    rating: 4.7,
    reviewCount: 48,
  },
  {
    id: "perform-tablets",
    brand: "Man Matters",
    name: "PERFORM Vitality Tablets (2 months Pack)",
    price: 1199,
    mrp: 1398,
    concern: ["hormones", "energy"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["general health"],
    category: "performance",
    baseScore: 80,
    image: "https://i.mscwlns.co/products/wp-content/2020/06/2-month-kitMob-view.jpg",
    url: "https://manmatters.com/perform-tablets",
    rating: 3.9,
    reviewCount: 119,
  },
  {
    id: "perform-energy-booster-60-effervescent-tablets",
    brand: "Man Matters",
    name: "PERFORM Energy Booster| 60 Effervescent Tablets",
    price: 1699,
    mrp: 1998,
    concern: ["hormones", "energy"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["general health"],
    category: "performance",
    baseScore: 80,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1606804095/Man%20Matters/PDP%20Filter/Effervescent%20Po3%20x2/Eff-tablets-_Pack-of-3_-x2_1600X1200.jpg?tr=w-800",
    url: "https://manmatters.com/perform-energy-booster-60-effervescent-tablets",
  },
  // ── SKIN ──
  {
    id: "facewash",
    brand: "Man Matters",
    name: "Men's Face Wash for Oily Skin",
    price: 349,
    mrp: 349,
    concern: ["skin"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["acne", "oily skin"],
    category: "skin",
    baseScore: 80,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/1182231/Saly%20open%20%281%29-compressed_3tvxc2.jpg?tr=w-600",
    url: "https://manmatters.com/facewash",
    rating: 4.4,
    reviewCount: 44,
  },
  {
    id: "salicylic-acid-face-wash",
    brand: "Man Matters",
    name: "Salicylic Acid Face Wash",
    price: 349,
    mrp: 349,
    concern: ["skin"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["general health"],
    category: "skin",
    baseScore: 80,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1605070880/Man%20Matters/Card%20image%20change/Skin/face%20wash/Anti-Acne-Face-Wash_1600X1200.jpg?tr=w-800",
    url: "https://manmatters.com/salicylic-acid-face-wash",
  },
  {
    id: "skin-dermaroller",
    brand: "Man Matters",
    name: "Derma Roller for Skin",
    price: 399,
    mrp: 399,
    concern: ["skin"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["acne", "oily skin"],
    category: "skin",
    baseScore: 80,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1604476909/Man%20Matters/Random/Activator-mobile.jpg?tr=w-800",
    url: "https://manmatters.com/skin-dermaroller",
    rating: 3.6,
    reviewCount: 13,
  },
  {
    id: "sunscreen",
    brand: "Man Matters",
    name: "Sunscreen SPF50",
    price: 449,
    mrp: 449,
    concern: ["skin"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["general health"],
    category: "skin",
    baseScore: 80,
    image: "https://i.mscwlns.co/media/misc/others/Slide-1%20%282%29_lrqk11.jpg?tr=w-600",
    url: "https://manmatters.com/sunscreen",
  },
  {
    id: "skin-cream",
    brand: "Man Matters",
    name: "REJUV Under Eye Cream",
    price: 499,
    mrp: 499,
    concern: ["skin"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["general health"],
    category: "skin",
    baseScore: 80,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/5369912/Under%20eye%20cream_5irad7.jpg?tr=w-600",
    url: "https://manmatters.com/skin-cream",
    rating: 4.0,
    reviewCount: 22,
  },
  {
    id: "skin-serum",
    brand: "Man Matters",
    name: "REJUV Niacinamide Serum",
    price: 549,
    mrp: 549,
    concern: ["skin"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["general health"],
    category: "skin",
    baseScore: 80,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/1254313/Rejuv%20face%20serum_lq9vu6.jpg?tr=w-600",
    url: "https://manmatters.com/skin-serum",
    rating: 4.3,
    reviewCount: 87,
  },
  {
    id: "rejuv-anti-aging-oil-for-men",
    brand: "Man Matters",
    name: "REJUV Anti Aging Oil For Men",
    price: 599,
    mrp: 599,
    concern: ["skin"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["general health"],
    category: "skin",
    baseScore: 82,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1604746001/Man%20Matters/Card%20image%20change/Skin/CBD%20Oil/Rejuv_Anti_Aging_Oil_1600X1200_1.jpg?tr=w-800",
    url: "https://manmatters.com/rejuv-anti-aging-oil-for-men",
    rating: 4.6,
    reviewCount: 52,
  },
  {
    id: "nourish-skin-gummies-2-month-pack-60-gummies",
    brand: "Man Matters",
    name: "Nourish Skin Gummies| 2 Month Pack| 60 Gummies",
    price: 799,
    mrp: 898,
    concern: ["skin"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["general health"],
    category: "skin",
    baseScore: 80,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1605071056/Man%20Matters/Card%20image%20change/Skin/Gummies%202m/Skin-Gummies-2M_1600x1200.jpg?tr=w-800",
    url: "https://manmatters.com/nourish-skin-gummies-2-month-pack-60-gummies",
  },
  // ── SLEEP ──
  {
    id: "relax-melatonin-strips",
    brand: "Man Matters",
    name: "Relax Melatonin Strips",
    price: 299,
    mrp: 299,
    concern: ["sleep"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["general health"],
    category: "sleep",
    baseScore: 80,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1604746834/Man%20Matters/Card%20image%20change/sleep/strips/Relax-Melatonin-Strips_1600X1200.jpg?tr=w-800",
    url: "https://manmatters.com/relax-melatonin-strips",
    rating: 3.5,
    reviewCount: 16,
  },
  {
    id: "calm-sleep-tea",
    brand: "Man Matters",
    name: "CALM Sleep Tea",
    price: 349,
    mrp: 349,
    concern: ["sleep"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["general health"],
    category: "sleep",
    baseScore: 90,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1604746889/Man%20Matters/Card%20image%20change/sleep/tea/CALM-Sleep-Tea_1600X1200.jpg?tr=w-800",
    url: "https://manmatters.com/calm-sleep-tea",
    rating: 5.0,
    reviewCount: 5,
  },
  {
    id: "relax-sleep-tablets",
    brand: "Man Matters",
    name: "Relax Sleep Tablets",
    price: 399,
    mrp: 399,
    concern: ["sleep"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["general health"],
    category: "sleep",
    baseScore: 84,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1604746863/Man%20Matters/Card%20image%20change/sleep/tablets/Sleep-Tablets_1600X1200.jpg?tr=w-800",
    url: "https://manmatters.com/relax-sleep-tablets",
    rating: 4.7,
    reviewCount: 7,
  },
  {
    id: "relax-sleep-gummies",
    brand: "Man Matters",
    name: "Relax Sleep Gummies",
    price: 499,
    mrp: 499,
    concern: ["sleep"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["general health"],
    category: "sleep",
    baseScore: 80,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1634812319/Man%20Matters/Relax%20Sleep%20Gummies/Product%20Images/Sleep-Gummies_1600X1200.jpg?tr=w-800",
    url: "https://manmatters.com/relax-sleep-gummies",
    rating: 4.3,
    reviewCount: 26,
  },
  // ── WEIGHT ──
  {
    id: "lean-weight-tablets",
    brand: "Man Matters",
    name: "LEAN Weight Tablets",
    price: 349,
    mrp: 349,
    concern: ["weight"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["general health"],
    category: "weight",
    baseScore: 80,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1604747048/Man%20Matters/Card%20image%20change/weight/tabs/Weight-Tablets_1600X1200.jpg?tr=w-800",
    url: "https://manmatters.com/lean-weight-tablets",
    rating: 4.4,
    reviewCount: 44,
  },
  {
    id: "apple-cider-vinegar-gummies-30-gummies",
    brand: "Man Matters",
    name: "Apple Cider Vinegar Gummies| 30 Gummies",
    price: 599,
    mrp: 599,
    concern: ["weight"],
    gender: ["male"],
    segment: ["male-18-25", "male-25-35", "male-35-plus"],
    followUp: ["general health"],
    category: "weight",
    baseScore: 80,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1598394816/Man%20Matters/ACV%20Gummies/29.png?tr=w-800",
    url: "https://manmatters.com/apple-cider-vinegar-gummies-30-gummies",
  },
];

// 50 products total