// Auto-generated from response.json — Mosaic Wellness product catalog
// Man Matters · Be Bodywise · Little Joys

export interface LocalProduct {
  id: string;
  handle: string;
  title: string;
  brand: string;
  description: string;
  price: number;
  compareAtPrice: number | null;
  discountPct: number;
  image: string | null;
  ingredients: string[];
  usage: string[];
  forWith: { for: string; with: string } | null;
  concern: string;
  tags: string[];
  available: boolean;
  rating: number;
  isKit: boolean;
}

export const localProducts: LocalProduct[] = [
  {
    id: "biotin-multivitamin-hair-gummies-2m",
    handle: "biotin-multivitamin-hair-gummies-2m",
    title: "Be Bodywise Biotin Hair Gummies (60)",
    brand: "Be Bodywise",
    description: "For Mothers Use – Not Suitable for Children Our Hair Gummies are enriched with Biotin, Zinc & essential Multivitamins giving you the right nutrition to protect your hair from within🥦 Use consistently for at least 3 months for best results 💆🏻‍♀️ Reduces & prevents hair fall 💯 Strengthens and nourishes hair 🌟 Repairs dry, dull & damaged hair The best, tastiest and long-lasting solution for healthier hair! Suitable for 18+ women for all hair concerns & hair types Take 1 gummy everyday, after any me",
    price: 849,
    compareAtPrice: 999,
    discountPct: 15,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/biotin-multivitamin-hair-gummies-2m/1__6__PXJj7mtVL.jpg?tr=w-600",
    ingredients: ["Biotin", "Zinc & Multivitamins"],
    usage: ["Eat 1 gummy daily after a meal."],
    forWith: { for: "Hair growth & strength", with: "Biotin, Multivitamins, Zinc" },
    concern: "hair",
    tags: ["MC - Others", "hair", "Be Bodywise"],
    available: false,
    rating: 4.0,
    isKit: false,
  },
  {
    id: "1-salicylic-acid-body-wash-bb",
    handle: "1-salicylic-acid-body-wash-bb",
    title: "1% Salicylic Acid Body Wash",
    brand: "Be Bodywise",
    description: "For Mothers Use – Not Suitable for Children 1% Salicylic Acid Body Wash helps to: 🌟 Exfoliate &amp; remove dead skin cells 🌟 Prevent body acne by unclogging pores 🌟 Improve Strawberry Skin appearance over time when used with Lactic Acid Lotion 🌟 Give you cooling sensation and leave you refreshed with every wash ✅ Use twice daily for 3 months for best results🗓️",
    price: 349,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/1-salicylic-acid-body-wash/Artboard%201%20%283%29_7n5i1p.jpg?tr=w-6000",
    ingredients: ["1% Salicylic Acid", "Chamomile Extract"],
    usage: ["For 30 days - Take 1 gummy every day after breakfast."],
    forWith: { for: "Preventing Body Acne", with: "1% Salicylic acid, Chamomile" },
    concern: "skin",
    tags: ["skin", "Be Bodywise"],
    available: true,
    rating: 4.0,
    isKit: false,
  },
  {
    id: "5-niacinamide-body-wash-bb",
    handle: "5-niacinamide-body-wash-bb",
    title: "5% Niacinamide Body Wash",
    brand: "Be Bodywise",
    description: "For Mothers Use – Not Suitable for Children 👩‍⚕️#1 Doctor recommended solution for dull skin. 5% Niacinamide Body Wash deep cleanses, removes dry patches and strengthens skin's moisture barrier 🌟Deep cleanses skin: Deep cleanses pores by reducing sebum production and removing impurities 🌟 Evens skin: Niacinamide and Aloe Vera help battle hyperpigmentation & skin discoloration 🌟 Provides intense hydration: Niacinamide is a natural humectant, i.e. it pulls moisture from the environment keeping ski",
    price: 349,
    compareAtPrice: 399,
    discountPct: 12,
    image: "https://i.mscwlns.co/media/misc/pdp/5-niacinamide-body-wash/7__2__I0i9kF8aJ.png?tr=w-600",
    ingredients: ["5% Niacinamide", "Aloe Vera"],
    usage: ["For 30 days - Take 1 gummy every day after breakfast."],
    forWith: { for: "Uneven Skin", with: "5% Niacinamide, Aloe Vera" },
    concern: "skin",
    tags: ["skin", "Be Bodywise"],
    available: true,
    rating: 4.0,
    isKit: false,
  },
  {
    id: "snail-96-mucin-serum-bb",
    handle: "snail-96-mucin-serum-bb",
    title: "Snail 96 Mucin Serum (100ml)",
    brand: "Be Bodywise",
    description: "For Mothers Use – Not Suitable for Children Snail 96 Mucin Serum is a non-comedogenic formula that helps repair your skin barrier leaving your skin radiant and dewy 🌟 This Korean skincare secret specifically made for all Indian skin types and helps to ⬇️ ✅Provide deep hydration ✅Fade dark spots and acne marks ✅Improve skin texture ✅Diminish fine lines and wrinkles ✅Slow down signs of ageing by boosting collagen production Based on a customer study, 91% of Indian women found this serum smoother a",
    price: 799,
    compareAtPrice: 899,
    discountPct: 11,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/snail-96-mucin-serum/Artboard%201%20%286%29_89ksvx.jpg?tr=w-600",
    ingredients: ["96% Pure Snail Mucin", "D-Panthenol", "Aloe Vera Extract"],
    usage: ["For 30 days - Take 1 gummy every day after breakfast."],
    forWith: { for: "Glowing & Brightening Skin", with: "Vit C, Ferulic Acid" },
    concern: "skin",
    tags: ["skin", "Be Bodywise"],
    available: false,
    rating: 4.0,
    isKit: false,
  },
  {
    id: "acne-control-wash-bb",
    handle: "acne-control-wash-bb",
    title: "1% Salicylic Acid Face Wash (Foam-Based)",
    brand: "Be Bodywise",
    description: "For Mothers Use – Not Suitable for Children 👩🏽‍🍼 Great for moms who are looking for a foam-based face-wash that doesn't dry their skin 🔴 Reduces Acne: This 1% Salicylic Acid Face Wash (Foam-Based) with Glycolic Acid is the first step in a routine targetted at reducing acne and comedones. 🧽 Exfoliates Dead Skin Cells: Glycolic and Salicylic acids are chemical exfoliants with antibacterial properties. 1% Salicylic Acid Face Wash (Foam-Based) unclogs pores, gently removes build-up & blackheads and ",
    price: 349,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/media/misc/pdp/salicylic-acid-face-wash/1SAFW_UBHYBP7yM.png?tr=w-800",
    ingredients: [],
    usage: ["For 30 days - Take 1 gummy every day after breakfast."],
    forWith: { for: "Acne prone skin", with: "Salicyclic acid, Glycolic acid" },
    concern: "skin",
    tags: ["skin", "Be Bodywise"],
    available: true,
    rating: 4.0,
    isKit: false,
  },
  {
    id: "2-aha-body-wash-bb",
    handle: "2-aha-body-wash-bb",
    title: "2% AHA Body Wash",
    brand: "Be Bodywise",
    description: "For Mothers Use – Not Suitable for Children ▶Deep cleanses skin : Glycolic Acid in this AHA body wash deep cleanses pores by gently exfoliating dead skin cells and removing impurities. ▶Improves skin cell turnover : Lactic Acid helps boost collagen production, i.e. post exfoliation - it helps surface the new skin much faster ▶Provides intense hydration and nourishes the skin: Glycerine is a natural humectant, i.e. it pulls moisture from the environment keeping skin soft and supple ▶Leaves you re",
    price: 349,
    compareAtPrice: 399,
    discountPct: 12,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/2-aha-body-wash/7__7__ZLh05Dmr0.png?tr=w-600",
    ingredients: ["4% Glycerin", "Lactic Acid", "Glycolic Acid", "Aloe Vera", "Grapeseed Extract"],
    usage: ["For 30 days - Take 1 gummy every day after breakfast."],
    forWith: { for: "Skin cell turnover & Cleansing", with: "2% AHA" },
    concern: "wellness",
    tags: ["wellness", "Be Bodywise"],
    available: true,
    rating: 4.0,
    isKit: false,
  },
  {
    id: "4-aha-bha-underarm-roll-on-bb",
    handle: "4-aha-bha-underarm-roll-on-bb",
    title: "4% AHA BHA Underarm Roll On",
    brand: "Be Bodywise",
    description: "For Mothers Use – Not Suitable for Children Want to feel fresh & odour-free all day ?🤩 Our 4% AHA BHA Underarm Roll On helps to: 🌟 Control body odour : 1% Salicylic Acid reduces bacterial overgrowth 🌟 Fresh for 12 hours : AHAs & BHAs keep you fresh & odour free till your day-end 🌟 Reduce pigmentation over time : 1% Mandelic Acid and Alpha Arbutin seep under the skin and slow down melanin production from within Roll On works on Mild Pigmentation. ❌ You will not see results in just 1 month ✅ Use t",
    price: 349,
    compareAtPrice: 399,
    discountPct: 12,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/4-aha-bha-underarm-roll-on/CR%2059_AJ_Flora_1c8sbd.jpg?tr=w-600",
    ingredients: ["1% Salicylic Acid", "1% Mandelic Acid", "2% Lactic Acid"],
    usage: ["For 30 days - Take 1 gummy every day after breakfast."],
    forWith: { for: "Underarm Odour, Pigmentation", with: "1% Salicylic acid, Chamomile" },
    concern: "wellness",
    tags: ["wellness", "Be Bodywise"],
    available: true,
    rating: 4.0,
    isKit: false,
  },
  {
    id: "niacinamide-body-lotion-bb",
    handle: "niacinamide-body-lotion-bb",
    title: "10% Niacinamide Body Lotion",
    brand: "Be Bodywise",
    description: "For Mothers Use – Not Suitable for Children ▶ Repairs moisture barrier: Niacinamide & aloe assist in keeping the natural barrier of the skin healthy & repairing compromised barrier ▶ Reduces acne marks & blemishes: 10% Niacinamide suppresses melanin transfer to reduce the appearance of marks gradually ▶ Nourishes skin: Made with a combination of different emollients & humectants, this lotion keeps the skin supple and healthy Suitable for all skin types Patch test is recommended Use everyday afte",
    price: 449,
    compareAtPrice: 499,
    discountPct: 10,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1658497292/staging/products/niacinamide-body-lotion/CAROUSEL/0-1.png?tr=w-800",
    ingredients: [],
    usage: ["For 30 days - Take 1 gummy every day after breakfast."],
    forWith: { for: "Acne Marks, Nourishing Skin", with: "10% Niacinamide, Aloe Vera" },
    concern: "skin",
    tags: ["skin", "Be Bodywise"],
    available: true,
    rating: 4.0,
    isKit: false,
  },
  {
    id: "sunscreen-gel-spf-50-bb",
    handle: "sunscreen-gel-spf-50-bb",
    title: "Sunscreen Gel with SPF 50",
    brand: "Be Bodywise",
    description: "For Mothers Use – Not Suitable for Children Gel based chemical sunscreen with SPF 50 provides Broad Spectrum & Photo-Damaging protection. It is powered by Kojic Acid & Niacinamide which helps in evening skin tone and prevents tan. Glycerin helps to moisturise and hydrate the skin.🌟 ➡️Provides Broad Spectrum PA+++ Protection (UVA & UVB rays protection) ➡️Protects from Photo-Damaging: Premature ageing of skin due to sun exposure ➡️Prevents tanning caused by sun exposure ➡️Moisturizes, hydrates and",
    price: 499,
    compareAtPrice: 549,
    discountPct: 9,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/sunscreen-gel-spf-50/For%20%285%29_1acbmm.png?tr=w-600",
    ingredients: [],
    usage: ["For 30 days - Take 1 gummy every day after breakfast."],
    forWith: { for: "Sun & blue light protection", with: "Avobenzone, Titanium Dioxide" },
    concern: "wellness",
    tags: ["wellness", "Be Bodywise"],
    available: false,
    rating: 4.0,
    isKit: false,
  },
  {
    id: "skin-clarifying-bb",
    handle: "skin-clarifying-bb",
    title: "10% Niacinamide Serum",
    brand: "Be Bodywise",
    description: "For Mothers Use – Not Suitable for Children Dermatologist Recommended Niacinamide Serum in India Fades Acne Marks and dark spots: 10% Niacinamide breaks down excess melanin to minimise the appearance of acne marks, blemishes, dark spots and pigmentation Improves Skin Texture: 10% Niacinamide reduces the appearance of enlarged pores and evens skin tone resulting in improved skin texture. Reduces inflammation: 1% Zinc PCA and Green Tea Extract soothe the skin and reduce inflammation caused by acne",
    price: 489,
    compareAtPrice: 599,
    discountPct: 18,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1631345517/staging/products/skin-clarifying/0_BLUE/CAROUSEL2/00.png?tr=w-800",
    ingredients: [],
    usage: ["For 30 days - Take 1 gummy every day after breakfast."],
    forWith: { for: "Acne Marks, Hyperpigmentation", with: "10% Niacinamide, 1% Zinc PCA" },
    concern: "skin",
    tags: ["skin", "Be Bodywise"],
    available: false,
    rating: 4.0,
    isKit: false,
  },
  {
    id: "skin-rejuvenation-serum-bb",
    handle: "skin-rejuvenation-serum-bb",
    title: "20% Vitamin C Face Serum",
    brand: "Be Bodywise",
    description: "For Mothers Use – Not Suitable for Children 🍊Dermatologist Recommended Vitamin C Serum in India 🧪Enhances Skin Glow: It targets dull skin and uneven skin tone by inhibiting melanin production, which helps in brightening dark spots and enhancing skin glow & radiance. 👩🏽Reduces Wrinkles & Fine Lines: This face serum for women minimizes the appearance of blemishes, fine lines, and wrinkles, providing the skin with the essential nutrients and vitamins for glowing skin and a radiant look. 🍋 Prevents ",
    price: 599,
    compareAtPrice: 699,
    discountPct: 14,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1636476706/staging/products/skin-rejuvenation-serum/0_BLUE/CAROUSEL3/0_VitC.png?tr=w-800",
    ingredients: [],
    usage: ["For 30 days - Take 1 gummy every day after breakfast."],
    forWith: { for: "Glowing & Brightening Skin", with: "Vit C, Ferulic Acid" },
    concern: "wellness",
    tags: ["wellness", "Be Bodywise"],
    available: false,
    rating: 4.0,
    isKit: false,
  },
  {
    id: "2-salicylic-acid-face-wash-bb",
    handle: "2-salicylic-acid-face-wash-bb",
    title: "2% Salicylic Acid Face Wash",
    brand: "Be Bodywise",
    description: "For Mothers Use – Not Suitable for Children 👩🏽‍🍼 Great for moms who are looking for a face-wash that doesn't dry their skin 🧽Deep cleanses skin: Formulated with 2% Salicylic Acid - a potent BHA - this face wash exfoliates dead skin cells and removes excess oil, dirt and other impurities. 🔴Prevents acne formation: Salicylic acid unclogs pores and regulates sebum production thereby reducing acne formation. 🧫 Reduces blackheads: Blackheads are caused due to clogged pores. This facial cleanser with ",
    price: 299,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1641555842/staging/products/2-salicylic-acid-face-wash/CAROUSEL/0.png?tr=w-800",
    ingredients: [],
    usage: ["For 30 days - Take 1 gummy every day after breakfast."],
    forWith: { for: "Acne-Prone skin", with: "2% Salicylic acid, Allantoin" },
    concern: "skin",
    tags: ["skin", "Be Bodywise"],
    available: true,
    rating: 4.0,
    isKit: false,
  },
  {
    id: "benzoyl-peroxide-facewash-bb",
    handle: "benzoyl-peroxide-facewash-bb",
    title: "2.5% Benzoyl Peroxide Facewash",
    brand: "Be Bodywise",
    description: "For Mothers Use – Not Suitable for Children 2.5% Benzoyl Peroxide Face Wash is a creamy and gentle face wash 🌟 It helps to ⬇️ ✅Deep cleanse pores from within ✅Reduce sebum production ✅Kill acne-causing bacteria ✅Prevent acne formation ➡️Use it everyday for 3 months to see visible results. ⚠️ We recommend doing a patch test",
    price: 349,
    compareAtPrice: 399,
    discountPct: 12,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/benzoyl-peroxide-facewash/Artboard%201%20%284%29_7fm1zd.jpg?tr=w-800",
    ingredients: [],
    usage: ["For 30 days - Take 1 gummy every day after breakfast."],
    forWith: { for: "Reducing Pigmentation", with: "Lactic Acid, Urea & Kojic Acid" },
    concern: "wellness",
    tags: ["wellness", "Be Bodywise"],
    available: true,
    rating: 4.0,
    isKit: false,
  },
  {
    id: "ice-roller-bb",
    handle: "ice-roller-bb",
    title: "Ice Roller | 1 N",
    brand: "Be Bodywise",
    description: "For Mothers Use – Not Suitable for Children Moms: you need some SELF CARE time! 🧊 Use consistently for at least 3 months for best results 😁Reduces face and under-eye puffiness 🩸Boosts blood circulation ❤️Minimises redness 🧖‍♀️Tightens pores 🌟Soothes skin Got hurt? You can use this tool to ice the affected area!",
    price: 349,
    compareAtPrice: 499,
    discountPct: 30,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/ice-roller/Artboard%201%20%288%29_a8kf19.jpg?tr=w-800",
    ingredients: [],
    usage: ["For 30 days - Take 1 gummy every day after breakfast."],
    forWith: { for: "Reducing Pigmentation caused b", with: "Lactic Acid, Urea & Kojic Acid" },
    concern: "wellness",
    tags: ["wellness", "Be Bodywise"],
    available: true,
    rating: 4.0,
    isKit: false,
  },
  {
    id: "5-lactic-acid-body-lotion-bb",
    handle: "5-lactic-acid-body-lotion-bb",
    title: "5% Lactic Acid Body Lotion",
    brand: "Be Bodywise",
    description: "For Mothers Use – Not Suitable for Children 🧪 Improvement in texture : Lactic Acid- a potent AHA helps remove the accumulated dead cells on skin and stimulates cell renewal which helps reduce bumps and enhance texture 💪🏼Nourishes skin: Enriched with Cica Extract and Aloe Vera, the lotion hydrates skin and improves the skin elasticity to make your skin look supple 🍓Helps improve the appearance of strawberry legs and keratosis pilaris: Lactic acid helps with gentle exfoliation and the moisturing a",
    price: 449,
    compareAtPrice: 499,
    discountPct: 10,
    image: "https://i.mscwlns.co/media/bebodywise/pdp/5-lactic-acid-body-lotion/carousel/0_2_A5WHgRf5IG.png?tr=w-800",
    ingredients: [],
    usage: ["For 30 days - Take 1 gummy every day after breakfast."],
    forWith: { for: "Improving Skin Texture", with: "5% Lactic Acid, Cica Extract" },
    concern: "wellness",
    tags: ["wellness", "Be Bodywise"],
    available: true,
    rating: 4.0,
    isKit: false,
  },
  {
    id: "10-aha-body-scrub-bb",
    handle: "10-aha-body-scrub-bb",
    title: "10% AHA Body Scrub (200g)",
    brand: "Be Bodywise",
    description: "For Mothers Use – Not Suitable for Children 🧪 Exfoliates dead skin cells: This deep-cleansing body scrub contains natural silica beads, which help exfoliate dead skin cells and remove impurities. 🧴 Removes tan: Removal of dead skin cells in this lactic acid body scrub removes tan, revealing a better skin complexion 📉 Visibly reduces ingrown hair: When used over time, 10% Lactic Acid and Oat Extract in this body scrub help deep cleanse pores exposing healthy layers of skin, boosting cell turnover",
    price: 499,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/media/misc/pdp_rcl/10-aha-body-scrub/1000x750__2__ce1Z0jI-9.jpg?tr=w-800",
    ingredients: [],
    usage: ["For 30 days - Take 1 gummy every day after breakfast."],
    forWith: { for: "Exfoliation & Strawberry Legs", with: "1% Salicylic acid, Chamomile" },
    concern: "wellness",
    tags: ["wellness", "Be Bodywise"],
    available: true,
    rating: 4.0,
    isKit: false,
  },
  {
    id: "hair-health-gummies-bb",
    handle: "hair-health-gummies-bb",
    title: "Biotin Hair Gummies (30)",
    brand: "Be Bodywise",
    description: "Bring Back Your Hair. And the Confidence That Came With It. ⚠️ A daily self-care win in a gummy made for mothers. Formulated with 100% RDA Biotin, a key nutrient that supports the natural production of keratin the protein that keeps hair, skin, and nails healthy. Because being a mom shouldn’t mean putting yourself last. These Biotin Gummies are your guilt-free ritual to reclaim stronger hair, glowing skin and a little joy for yourself. Here’s what’s inside: ✅ 100% RDA Biotin (B7) — supports stro",
    price: 499,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/media/misc/pdp/hair-health-gummies-moms/Thumbnail%20Images%20Biotin_2g6fj6.png?tr=w-600",
    ingredients: ["Biotin", "Zinc & Multivitamins", "Chicory Root"],
    usage: ["For 30 days - Take 1 gummy every day after breakfast."],
    forWith: { for: "Hair & Skin", with: "Biotin & Vitamin E" },
    concern: "hair",
    tags: ["hair", "Be Bodywise"],
    available: true,
    rating: 4.0,
    isKit: false,
  },
  {
    id: "vegan-plant-protein-powder-bb",
    handle: "vegan-plant-protein-powder-bb",
    title: "Vegan Plant Protein Powder",
    brand: "Be Bodywise",
    description: "For Mothers Use – Not Suitable for Children What makes this protein powder so good for moms? 💪🏽 Muscle Toning & Curbing Hunger Pangs Proteins are the building blocks for muscles. Our chocolate protein powder for moms has a blend of 4 Plant-based Proteins: pea, brown rice, moong bean, spirulina. Consuming an adequate amount of protein helps with muscle toning. With has 24g of protein, it controls hunger pangs making it ideal for weight management. 🦴 Bone Density & Health Post-pregnancy, many wome",
    price: 1199,
    compareAtPrice: 1599,
    discountPct: 25,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1636541751/staging/products/Protein/1_1000x750.png?tr=w-800",
    ingredients: ["4-Plant Based Proteins", "28 Vitamins and Minerals", "9 Amino Acids"],
    usage: ["For 30 days - Take 1 gummy every day after breakfast."],
    forWith: { for: "Muscle toning, Bone Density", with: "4-Plant Proteins, 28 Vitamins" },
    concern: "fitness",
    tags: ["fitness", "Be Bodywise"],
    available: false,
    rating: 4.0,
    isKit: false,
  },
  {
    id: "skin-health-gummies-bb",
    handle: "skin-health-gummies-bb",
    title: "Skin Health Gummies (30)",
    brand: "Be Bodywise",
    description: "For Mothers Use – Not Suitable for Children Skin Health Gummies are enriched with Hyaluronic Acid, Vitamin C, Vitamin E and Curcumin (Haldi) Extract. 🍎🥦 It helps to: 💦 Hydrate Skin 🧏🏻‍♀️Increase Skin Elasticity 🌟Enhance Skin Glow 👩🏻Reduce Wrinkles & Fine Lines Suitable for 18+ women and every skin type Take 1 gummy every day, after any meal💫 Use consistently for at least 3 months for best results It's Breastfeeding Safe 🤱🏻",
    price: 499,
    compareAtPrice: 599,
    discountPct: 16,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1657629174/staging/products/skin-health-gummies/0_BLUE/Carousel_New_12July%2722/1_Skin_G.png?tr=w-800?tr=w-800",
    ingredients: [],
    usage: ["For 30 days - Take 1 gummy every day after breakfast."],
    forWith: { for: "Glowing and Hydrating Skin", with: "Hyaluronic Acid, Vitamin C" },
    concern: "skin",
    tags: ["skin", "Be Bodywise"],
    available: true,
    rating: 4.7,
    isKit: false,
  },
  {
    id: "active-assist-acv-gummies",
    handle: "active-assist-acv-gummies",
    title: "Apple Cider Vinegar Gummies (30)",
    brand: "Be Bodywise",
    description: "For Mothers Use – Not Suitable for Children ACV Gummies for Weight Loss & Gut Health: Fat Burner for Women How will these gummies help you? Good gut health: Did you know? A healthy gut can help you absorb more nutrients and lose weight! These ACV gummies are enriched with inulin which promote good gut health and help you lose weight. Boosts metabolism and controls appetite: ACV will prevent you from binge eating! Yes, these ACV gummies will promote a feeling of satiety and fullness and boost you",
    price: 599,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1640076363/staging/products/active-assist-acv-gummies/0_ACV/CAROUSEL/0.jpg?tr=w-800?tr=w-800",
    ingredients: [],
    usage: ["For 90 days - Take 1 gummy every day after breakfast."],
    forWith: { for: "Gut health improvement", with: "Apple Cider Vinegar, Inulin" },
    concern: "wellness",
    tags: ["wellness", "Be Bodywise"],
    available: true,
    rating: 4.7,
    isKit: false,
  },
  {
    id: "calcium-gummies-moms-bb",
    handle: "calcium-gummies-moms-bb",
    title: "Calcium Gummies for Moms",
    brand: "Be Bodywise",
    description: "Support for Strong Bones & Stamina ⚠️ Calcium deficiency often goes unnoticed until the joint aches, low energy, and sluggish days begin. Between the school runs and housework, your body deserves a little backup. These Calcium Gummies are made for every mother who carries the weight of the home and still keep moving. Reclaim your strength from within. Here’s what’s inside: ✅ Calcium + Vegan D3 + B12 supports strong bones, steady energy, and daily stamina ✅ Chicory Root Prebiotic helps your body ",
    price: 549,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/media/misc/pdp/calcium-gummies-moms/Thumbnail%20Images%20Calcium_49gd2x.png?tr=w-600",
    ingredients: ["Calcium", "Vitamin D3 derived from Lichen", "Chicory Root (Prebiotic Fibre)"],
    usage: ["For 30 days - Take 1 gummy every day after breakfast."],
    forWith: { for: "Bone & Strength", with: "Calcium & Phosphate" },
    concern: "wellness",
    tags: ["wellness", "Be Bodywise"],
    available: true,
    rating: 4.0,
    isKit: false,
  },
  {
    id: "magnesium-gummies-30-bb",
    handle: "magnesium-gummies-30-bb",
    title: "Magnesium Gummies for Moms",
    brand: "Be Bodywise",
    description: "We teamed up with Be Bodywise to bring our moms clean, expert-backed care for better sleep and calmer days. Stressed, Anxious & Struggling to Sleep? You might need MAGNESIUM! ✨ Magnesium: The Overlooked Key to Sleep, Stress & Anxiety Relief ✨ Your body depends on it for relaxed nights & a peaceful mind 😊💤 How Does Magnesium Gummy Help You Sleep Better and STRESS LESS? 💤Supports melatonin production – your sleep hormone 🌿 Lowers cortisol – relieving stress 🧠 Supports GABA neurotransmitter – reduc",
    price: 599,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/media/misc/others/Magnesium%20Gummies%20for%20Moms_e71i5f.jpg?tr=w-600",
    ingredients: ["Magnesium", "Glycinate", "Chicory (Prebiotic Fibre)"],
    usage: ["For 30 days - Take 1 gummy every day after breakfast."],
    forWith: { for: "Sleep & Stress", with: "Magnesium Glycinate, Zinc" },
    concern: "wellness",
    tags: ["sleepmom", "momgummies", "wellness", "Be Bodywise"],
    available: false,
    rating: 4.0,
    isKit: false,
  },
  {
    id: "magnesium-gummies-moms-bb-60n",
    handle: "magnesium-gummies-moms-bb-60n",
    title: "Advanced Magnesium Gummies 60N",
    brand: "Be Bodywise",
    description: "We teamed up with Be Bodywise to bring our moms clean, expert-backed care for better sleep and calmer days. Stressed, Anxious OR Struggling to Sleep? It might be time to embrace the calming power of magnesium! Life as a mom can be demanding, and these Magnesium Gummies are designed to support your well-being, helping you with relaxed nights & a peaceful mind 😊 💤 Here's what makes them special: 💤 Supports melatonin production – your sleep hormone 🌿 Lowers cortisol – relieving stress 🧠 Supports GA",
    price: 1099,
    compareAtPrice: 1199,
    discountPct: 8,
    image: "https://i.mscwlns.co/media/misc/pdp/magnesium-gummies-moms-bb-60n/4%20%281%29_89ihtt.png?tr=w-600",
    ingredients: ["Magnesium", "Glycinate", "Chicory (Prebiotic Fibre)"],
    usage: ["For 30 days - Take 1 gummy every day after breakfast."],
    forWith: { for: "Sleep & Stress", with: "5-in-1 Magnesium" },
    concern: "wellness",
    tags: ["sleepmom", "momgummies", "wellness", "Be Bodywise"],
    available: true,
    rating: 4.0,
    isKit: false,
  },
  {
    id: "magnesium-gummies-mother",
    handle: "magnesium-gummies-moms-bb",
    title: "Magnesium Gummies for Moms (30N)",
    brand: "Be Bodywise",
    description: "We teamed up with Be Bodywise to bring our moms clean, expert-backed care for better sleep and calmer days. Stressed, Anxious OR Struggling to Sleep? It might be time to embrace the calming power of magnesium! Life as a mom can be demanding, and these Magnesium Gummies are designed to support your well-being, helping you with relaxed nights & a peaceful mind 😊 💤 Here's what makes them special: 💤 Supports melatonin production – your sleep hormone 🌿 Lowers cortisol – relieving stress 🧠 Supports GA",
    price: 649,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/media/misc/pdp/magnesium-gummies-moms-bb/magnesium%2030N%20thumbnail_8xpdpv.jpg?tr=w-600",
    ingredients: ["Magnesium", "Glycinate", "Chicory (Prebiotic Fibre)"],
    usage: ["For 30 days - Take 1 gummy every day after breakfast."],
    forWith: { for: "Sleep & Stress", with: "5-in-1 Magnesium" },
    concern: "wellness",
    tags: ["wellness", "Be Bodywise"],
    available: true,
    rating: 4.0,
    isKit: false,
  },
  {
    id: "2024455",
    handle: "2024455",
    title: "Hair Serum Stage 1 Kit (25-34)",
    brand: "Man Matters",
    description: "Hair Serum Stage 1 Kit (25-34)",
    price: 749,
    compareAtPrice: 1298,
    discountPct: 42,
    image: null,
    ingredients: [],
    usage: [],
    forWith: null,
    concern: "hair",
    tags: ["hair", "Man Matters"],
    available: true,
    rating: 4.0,
    isKit: true,
  },
  {
    id: "2024456",
    handle: "2024456",
    title: "Hair Serum Stage 1 Kit (35+)",
    brand: "Man Matters",
    description: "Hair Serum Stage 1 Kit (35+)",
    price: 949,
    compareAtPrice: 1598,
    discountPct: 40,
    image: null,
    ingredients: [],
    usage: [],
    forWith: null,
    concern: "hair",
    tags: ["hair", "Man Matters"],
    available: true,
    rating: 4.0,
    isKit: true,
  },
  {
    id: "2024457",
    handle: "2024457",
    title: "Minoxidil Stage 2 Kit (25-34)",
    brand: "Man Matters",
    description: "Minoxidil Stage 2 Kit (25-34)",
    price: 749,
    compareAtPrice: 1098,
    discountPct: 31,
    image: null,
    ingredients: [],
    usage: [],
    forWith: null,
    concern: "hair",
    tags: ["hair", "Man Matters"],
    available: true,
    rating: 4.0,
    isKit: true,
  },
  {
    id: "2024458",
    handle: "2024458",
    title: "Minoxidil Stage 2 Kit (35+)",
    brand: "Man Matters",
    description: "Minoxidil Stage 2 Kit (35+)",
    price: 899,
    compareAtPrice: 1398,
    discountPct: 35,
    image: null,
    ingredients: [],
    usage: [],
    forWith: null,
    concern: "hair",
    tags: ["hair", "Man Matters"],
    available: true,
    rating: 4.0,
    isKit: true,
  },
  {
    id: "2024459",
    handle: "2024459",
    title: "Minoxidil Stage 3 Kit (18-24)",
    brand: "Man Matters",
    description: "Minoxidil Stage 3 Kit (18-24)",
    price: 749,
    compareAtPrice: 1098,
    discountPct: 31,
    image: null,
    ingredients: [],
    usage: [],
    forWith: null,
    concern: "hair",
    tags: ["hair", "Man Matters"],
    available: true,
    rating: 4.0,
    isKit: true,
  },
  {
    id: "2024460",
    handle: "2024460",
    title: "Minoxidil Stage 3 Kit (25-34)",
    brand: "Man Matters",
    description: "Minoxidil Stage 3 Kit (25-34)",
    price: 899,
    compareAtPrice: 1398,
    discountPct: 35,
    image: null,
    ingredients: [],
    usage: [],
    forWith: null,
    concern: "hair",
    tags: ["hair", "Man Matters"],
    available: true,
    rating: 4.0,
    isKit: true,
  },
  {
    id: "2024461",
    handle: "2024461",
    title: "Minoxidil Stage 3 Kit (35+)",
    brand: "Man Matters",
    description: "Minoxidil Stage 3 Kit (35+)",
    price: 899,
    compareAtPrice: 1398,
    discountPct: 35,
    image: null,
    ingredients: [],
    usage: [],
    forWith: null,
    concern: "hair",
    tags: ["hair", "Man Matters"],
    available: true,
    rating: 4.0,
    isKit: true,
  },
  {
    id: "2024462",
    handle: "2024462",
    title: "Minoxidil Stage 4 Kit (18-24)",
    brand: "Man Matters",
    description: "Minoxidil Stage 4 Kit (18-24)",
    price: 749,
    compareAtPrice: 1098,
    discountPct: 31,
    image: null,
    ingredients: [],
    usage: [],
    forWith: null,
    concern: "hair",
    tags: ["hair", "Man Matters"],
    available: true,
    rating: 4.0,
    isKit: true,
  },
  {
    id: "2024463",
    handle: "2024463",
    title: "Minoxidil Stage 4 Kit (25-34)",
    brand: "Man Matters",
    description: "Minoxidil Stage 4 Kit (25-34)",
    price: 899,
    compareAtPrice: 1398,
    discountPct: 35,
    image: null,
    ingredients: [],
    usage: [],
    forWith: null,
    concern: "hair",
    tags: ["hair", "Man Matters"],
    available: true,
    rating: 4.0,
    isKit: true,
  },
  {
    id: "nutrimix-nutrition-powder",
    handle: "nutrimix-nutrition-powder",
    title: "NutriMix Nutrition Powder 3",
    brand: "Little Joys",
    description: "🌾 5g of protein per serving of Nutrimix, essential for kids aged 2-6 for for overall health and development. 🥛 Can be had as morning milk or a yummy afternoon milkshake! ⬆️ Healthy nutrition with plant-based protein sources like moong dal, peas and brown rice . 🛡️ Boosts immunity with superfoods like ragi & bajra and 23 vitamins & minerals. 💪🏼 Ensures healthy development with the goodness of almonds and walnuts . 🦴 Calcium to help build strong bones and DHA (omega3) for healthy brain development",
    price: 549,
    compareAtPrice: 649,
    discountPct: 15,
    image: "https://i.mscwlns.co/media/misc/others/Nutrimix%20Chocolate%20Nutrition%20Powder_aknw9r.jpg?tr=w-600",
    ingredients: [],
    usage: ["For 90 days - Add 2 scoops in 200ml of warm milk or water."],
    forWith: { for: "Overall Health & Development", with: "Ragi, Bajra & Oats" },
    concern: "wellness",
    tags: ["CHOCOLATE", "2+", "Height & Weight Gain", "Immunity", "Bone Health", "Picky Eating & Diet", "2-6nm", "MC - 2-6 yrs", "Nutrimix", "wellness", "Little Joys"],
    available: true,
    rating: 4.5,
    isKit: false,
  },
  {
    id: "multivitamin-gummies",
    handle: "multivitamin-gummies-pack-2",
    title: "Multivitamin Gummies (60)",
    brand: "Little Joys",
    description: "For best results, use consistently for 3 months ✅ 11+ vitamins & minerals for your little one's daily nutritional needs . 🍎 Contains 6 real fruits & vegetables ! Fulfills any nutrition gaps in diet due to fussy or picky eating. 🛡️ Contains Vitamin C, Turmeric (Haldi), Vitamin B12 & Zinc which are known to boost immunity. 🚫 ZERO ADDED SUGAR - Uses a prebiotic fibre chicory root as its base. Along with gut health and immunity benefits it provides natural sweetness to the gummy. 🚫 No artificial col",
    price: 749,
    compareAtPrice: 999,
    discountPct: 25,
    image: "https://i.mscwlns.co/media/misc/pdp/multivitamin-gummies-pack-2/multivitamin-gummies%202%2B%2060N_j34v8y.png?tr=w-600",
    ingredients: [],
    usage: [],
    forWith: { for: "Immunity & Overall Health", with: "Ragi, Spinach, Apples" },
    concern: "kids",
    tags: ["IMMUNITY", "2+", "2-6gm", "2-6", "Picky Eating & Diet", "Immunity", "multivitamingummies", "MC - Multivitamin", "kids", "Little Joys"],
    available: true,
    rating: 4.4,
    isKit: false,
  },
  {
    id: "multivitamin-gummies",
    handle: "multivitamin-gummies",
    title: "Multivitamin Gummies ",
    brand: "Little Joys",
    description: "For best results, use consistently for 3 months ✅ 11+ vitamins & minerals for your little one's daily nutritional needs . 🍎 Contains 6 real fruits & vegetables ! Fulfills any nutrition gaps in diet due to fussy or picky eating. 🛡️ Contains Vitamin C, Turmeric (Haldi), Vitamin B12 & Zinc which are known to boost immunity. 🚫 ZERO ADDED SUGAR - Uses a prebiotic fibre chicory root as its base. Along with gut health and immunity benefits it provides natural sweetness to the gummy. 🚫 No artificial col",
    price: 499,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/media/misc/others/Multivitamin%20Gummies%202%2B%20%2830%20Days%20Pack%29_lwfoq5.jpg?tr=w-600",
    ingredients: [],
    usage: ["For 90 days - Take 1 gummy every day after breakfast."],
    forWith: { for: "Picky Eaters", with: "Spinach, Carrots, Apples" },
    concern: "kids",
    tags: ["IMMUNITY", "2+", "2-6", "2-6gm", "Picky Eating & Diet", "Immunity", "multivitamingummies", "MC - Multivitamin", "kids", "Little Joys"],
    available: true,
    rating: 4.4,
    isKit: false,
  },
  {
    id: "eye-gummies",
    handle: "eye-gummies",
    title: "Eye Health Gummies",
    brand: "Little Joys",
    description: "► For Ages 2-12 ► Flavour: Strawberry ► Worried about your child’s screen time? Our eye vitamin gummies will protect from damage caused by digital eye strain, eye fatigue, dry eyes and headaches. ► Includes vitamin A, amla, vitamin C and Lutemax® 2020 (patented ingredient). ► Made with 0 added sugar, 4 vitamins & minerals and 4 fruits & veggies. 30 Gummies | No side effects | Paediatrician Recommended",
    price: 1,
    compareAtPrice: 499,
    discountPct: 99,
    image: "https://i.mscwlns.co/media/misc/pdp/eye-gummies/2.3_Eye_Health_Gummies_gE2p2YUFv.png?tr=w-600",
    ingredients: ["Lutemax\u00ae 2020", "Bilberry", "Amla"],
    usage: ["For 90 days - Take 1 gummy every day after breakfast."],
    forWith: { for: "Eye Health", with: "Amla & Carrots" },
    concern: "kids",
    tags: ["eyegummies", "MC - Eye Health", "kids", "Little Joys"],
    available: false,
    rating: 4.7,
    isKit: false,
  },
  {
    id: "effervescent-tablets",
    handle: "effervescent-tablets",
    title: "Effervescent Tablets",
    brand: "Little Joys",
    description: "► Pop one of our orange-flavored effervescent tablets into a glass of water, watch it fizz and gulp it down. We've made them dissolvable for digestive ease! ► These plant-based, sugar-free tablets are packed with vitamins and real fruits and veggies. 100% Veg | Pediatrician Recommended | No Side Effects",
    price: 6,
    compareAtPrice: 379,
    discountPct: 98,
    image: "https://i.mscwlns.co/media/misc/pdp/effervescent-tablets/MV-Effervescent-tablet_uZyzNx1vK.jpg?tr=w-600",
    ingredients: [],
    usage: ["For kids 2 years or older, drop an effervescent tablet in a glass of water, wait for 2 minutes"],
    forWith: { for: "Picky Eaters", with: "Mango, Spinach, Oranges" },
    concern: "kids",
    tags: ["kids", "Little Joys"],
    available: false,
    rating: 4.5,
    isKit: false,
  },
  {
    id: "nutrimix-nutrition-powder",
    handle: "nutrition-powder-multivitamin-gummies-kit",
    title: "Multivitamin Gummies (30) & NutriMix (400g)",
    brand: "Little Joys",
    description: "For best results, use both consistently for 3 months 💪 Immunity boosting ingredients like ragi, bajra and haldi 🍃 Nutrimix contains ragi, bajra, almonds, walnuts and a blend of plant proteins (moong, brown rice, peas). 🍎 Multivitamin Gummies contains 11 vitamins including Vitamin B12, Vitamin C, Haldi and Zinc , and real fruits & veggies. ►Kit Contents: Nutrimix Nutrition Powder (350g) + Multivitamin Gummies 2+ (30N) Naturally Sweetened | No Side Effects | Pediatrician Recommended",
    price: 949,
    compareAtPrice: 1198,
    discountPct: 20,
    image: "https://i.mscwlns.co/media/misc/pdp/multivitamin-gummies-nutrimix-300/Slide-1-Nutrimix_6ik6h1.jpg?tr=w-600",
    ingredients: [],
    usage: [],
    forWith: { for: "Immunity & Overall Health", with: "Ragi, Spinach, Apples" },
    concern: "kids",
    tags: ["immunity", "kids", "Little Joys"],
    available: true,
    rating: 4.5,
    isKit: true,
  },
  {
    id: "toy-soap",
    handle: "toy-soap",
    title: "Toy Soap",
    brand: "Little Joys",
    description: "► For Ages 2-5 Let’s make hygiene easy for parents and fun for kids! Our soap with an eraser toy is here to make bathing more joyful for your kiddo - a duo that’ll make your kids skin perfectly clean and their stationary box more fun.",
    price: 399,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/media/misc/pdp/toy-soap/Soap_2000x__1__8vULH6wKj.png?tr=w-600",
    ingredients: [],
    usage: ["Work the soap into a nice lather. Gently massage in a circular motion for about 30 seconds. Rinse with warm water."],
    forWith: { for: "Fun Bathing", with: "Moisturizing Ingredients" },
    concern: "wellness",
    tags: ["bathandbody", "wellness", "Little Joys"],
    available: false,
    rating: 4.8,
    isKit: false,
  },
  {
    id: "brain-booster-gummies",
    handle: "brain-booster-gummies",
    title: "Brain Health Gummies",
    brand: "Little Joys",
    description: "► For Ages 2+ ► Our DHA Brain Gummies boost memory, concentration and long term brain development! ► Powered by DHA & Choline + with 8 nutrients and 4 delicious fruits and veggies. ► Bonus? It has zero added sugar! 30 Gummies | 100% Safe | Pediatrician Recommended To be given only under medical advice by a physician or certified dietician or nutritionist for children 2–5 years.",
    price: 499,
    compareAtPrice: 549,
    discountPct: 9,
    image: "https://i.mscwlns.co/media/misc/others/DHA%20Omega3%20Brain%20Gummies%202%2B%20%2830N%29_47ta0n.jpg?tr=w-600",
    ingredients: [],
    usage: ["For 90 days - Take 1 gummy every day after breakfast."],
    forWith: { for: "Brain Development", with: "DHA Omega 3" },
    concern: "kids",
    tags: ["BRAIN HEALTH", "2+", "2-6gm", "2-6", "Focus & Memory", "braingummies", "MC - Brain Health", "kids", "Little Joys"],
    available: true,
    rating: 4.7,
    isKit: false,
  },
  {
    id: "multivitamin-gummies",
    handle: "multivitamin-gummies-pack-5",
    title: "Multivitamin Gummies - Pack of 5",
    brand: "Little Joys",
    description: "For fussy eaters! ► Zero added sugar Multivitamin gummies with 12 vitamins and minerals & 6 fruits and veggies. ► Contains turmeric (haldi), vitamin C for immunity. ► Bridges vitamin deficiencies and boosts overall wellbeing. ► Plant-based strawberry flavoured supplements. ► Perfect alternative for bitter vitamin syrups. No side effects | Paediatrician Recommended",
    price: 2000,
    compareAtPrice: 2495,
    discountPct: 19,
    image: "https://i.mscwlns.co/media/misc/pdp/multivitamin-gummies-pack-5/multivitamin-gummies-pack-5_4qf3rz.jpg?tr=w-600",
    ingredients: [],
    usage: [],
    forWith: { for: "Picky Eaters", with: "Spinach, Carrots & Apples" },
    concern: "kids",
    tags: ["2-6", "Picky Eating & Diet", "Immunity", "multivitamingummies", "kids", "Little Joys"],
    available: true,
    rating: 4.4,
    isKit: true,
  },
  {
    id: "multivitamin-gummies",
    handle: "multivitamin-gummies-pack-10",
    title: "Multivitamin Gummies - Pack of 10",
    brand: "Little Joys",
    description: "For fussy eaters! ► Zero added sugar Multivitamin gummies with 12 vitamins and minerals & 6 fruits and veggies. ► Contains turmeric (haldi), vitamin C for immunity. ► Bridges vitamin deficiencies and boosts overall wellbeing. ► Plant-based strawberry flavoured supplements. ► Perfect alternative for bitter vitamin syrups. No side effects | Paediatrician Recommended",
    price: 3500,
    compareAtPrice: 4990,
    discountPct: 29,
    image: "https://i.mscwlns.co/media/misc/pdp/multivitamin-gummies-pack-10/Multivitamin%20Gummies%20-%20Pack%20of%2010_1t89ue.jpg?tr=w-600",
    ingredients: [],
    usage: [],
    forWith: { for: "Picky Eaters", with: "Spinach, Carrots & Apples" },
    concern: "kids",
    tags: ["2-6", "Picky Eating & Diet", "Immunity", "multivitamingummies", "kids", "Little Joys"],
    available: true,
    rating: 4.4,
    isKit: true,
  },
  {
    id: "nutrimix-nutrition-powder",
    handle: "nutrimix-nutrition-powder-pack-2",
    title: "NutriMix - Pack of 2",
    brand: "Little Joys",
    description: "For best results, use consistently for 3 months ► For Ages 2-9 ► Naturally sweetened with jaggery and dates ► Contains Ragi, Bajra & Oats for digestive health ► Combination of Moong Dal, Brown Rice & Peas (plant based natural protein) to fuel a child’s growing body ► Protein content equivalent to 3 bowls of dal ► Includes almonds, walnuts, chia and flax seeds No side effects | Paediatrician Recommended | 800 grams | Chocolate Flavoured | Gluten Free",
    price: 999,
    compareAtPrice: 1398,
    discountPct: 28,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1659437466/Little%20Joys/PDP/Kits/NP2.jpg",
    ingredients: [],
    usage: [],
    forWith: { for: "Growth & Development", with: "Ragi, Bajra & Oats" },
    concern: "wellness",
    tags: ["2-6nm", "wellness", "Little Joys"],
    available: true,
    rating: 4.5,
    isKit: true,
  },
  {
    id: "eye-gummies",
    handle: "eye-gummies-pack-2",
    title: "Eye Health Gummies - Pack of 2",
    brand: "Little Joys",
    description: "► For Ages 2-12 ► Flavour: Orange ► Worried about your child’s screen time? Our eye vitamin gummies will protect from damage caused by digital eye strain, eye fatigue, dry eyes and headaches. ► Includes vitamin A, amla, vitamin C and Lutemax® 2020 (patented ingredient). ► Made with 0 added sugar, 4 vitamins & minerals and 4 fruits & veggies. 30 Gummies | No side effects | Paediatrician Recommended",
    price: 749,
    compareAtPrice: 798,
    discountPct: 6,
    image: "https://i.mscwlns.co/media/misc/others/Eye%20Health%20Gummies%20%2830N%29%20Pack%20of%202_hng3rb.jpg?tr=w-600",
    ingredients: [],
    usage: [],
    forWith: { for: "Eye Health", with: "Amla & Carrots" },
    concern: "kids",
    tags: ["2+gm", "2-6", "Screentime", "eyegummies", "kids", "Little Joys"],
    available: false,
    rating: 4.7,
    isKit: true,
  },
  {
    id: "nutrimix-nutrition-powder-and-eye-gummies-kit",
    handle: "nutrimix-nutrition-powder-and-eye-gummies-kit",
    title: "Eye Health Gummies (30) & NutriMix (400g)",
    brand: "Little Joys",
    description: "The perfect combination for Eye Health & Growth! ► Finding your little ones on their screens all day? Nourish their eyes with our eye vitamin gummies made of amla & bilberry to protect them from damage. ► Our NutriMix is naturally sweetened with jaggery. It contains Ragi, Bajra & Oats for digestive health and Moong Dal, Brown Rice & Peas (plant based natural protein) to fuel a child’s growing body. The protein content is equivalent to 3 bowls of dal and includes almonds, walnuts, chia and flax s",
    price: 949,
    compareAtPrice: 1198,
    discountPct: 20,
    image: "https://i.mscwlns.co/media/misc/pdp/eye-gummies-nutrimix-300g/WhatsApp%20Image%202023-08-29%20at%206.07.11%20PM_2l6c8u.jpeg?tr=w-800",
    ingredients: ["Lutemax\u00ae 2020", "Bilberry", "Amla"],
    usage: [],
    forWith: { for: "Eye Health, Growth", with: "Vitamins & Proteins" },
    concern: "wellness",
    tags: ["eyekit", "wellness", "Little Joys"],
    available: false,
    rating: 4.8,
    isKit: true,
  },
  {
    id: "soap-crayon",
    handle: "soap-crayon",
    title: "Soap Crayon",
    brand: "Little Joys",
    description: "► For Ages 2-5 Make handwashing fun and easy for your little one! Use our crayon handwash to draw on palms, and then wash under water for 20 seconds. Germs can remain on surfaces, toys and books for more than 24 hours and this can cause infections and viruses. Our crayon handwash will help make handwashing a regular habit for your little one and will protect against germs! Patent Pending.",
    price: 449,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/media/misc/others/Crayon%20Handwash%20-%20Set%20of%203_5n344f.jpg?tr=w-600",
    ingredients: [],
    usage: ["Use our crayon handwash to draw on palms, and then wash under water for 20 seconds."],
    forWith: { for: "Fun Handwashing", with: "Cleansing Ingredients" },
    concern: "wellness",
    tags: ["Bath & Body", "bathandbody", "MC - Bath & Body", "wellness", "Little Joys"],
    available: false,
    rating: 4.6,
    isKit: false,
  },
  {
    id: "soap-crayon-pack-2",
    handle: "soap-crayon-pack-2",
    title: "Soap Crayon - Set of 6",
    brand: "Little Joys",
    description: "Make handwashing fun and easy for your little one! Use our crayon handwash to draw on palms, and then wash under water for 20 seconds. Germs can remain on surfaces, toys and books for more than 24 hours and this can cause infections and viruses. Our crayon handwash will help make handwashing a regular habit for your little one and will protect against germs! Patent Pending.",
    price: 799,
    compareAtPrice: 998,
    discountPct: 19,
    image: "https://i.mscwlns.co/media/misc/pdp/soap-crayon-pack-2/Copy_of_Crayon_Handwash__1___GuUarcx8.png?tr=w-600",
    ingredients: [],
    usage: [],
    forWith: { for: "Fun Handwashing", with: "Cleansing Ingredients" },
    concern: "wellness",
    tags: ["Bath & Body", "bathandbody", "wellness", "Little Joys"],
    available: false,
    rating: 4.3,
    isKit: true,
  },
  {
    id: "multivitamin-chocolate",
    handle: "multivitamin-chocolate",
    title: "Multivitamin Chocolate",
    brand: "Little Joys",
    description: "Your kid is now going to love their multivitamins. 🍫 Our Multivitamin Chocolate is naturally sweetened by jaggery and contains 11 vitamins & minerals. 🌱 Contains Zinc for immunity, Vitamin D to improve bone health and Vitamin A for better eyesight. 💪🏼 Build your kid's immunity, strength and memory in this unique chocolate form! ⛔️ These Multivitamins contain zero white sugar and are naturally sweetened with jaggery, giving it a yummy chocolatey taste. 30 Chocolates | No refined sugar | Paediatri",
    price: 499,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/media/misc/others/Multivitamin%20Chocolate%20%2830N%29_i9rkzu.jpg?tr=w-600",
    ingredients: ["Vitamin A (Retinyl Palmitate), Vitamin B3 (Niacin), Vitamin B5 (Pantothenic Acid), Vitamin B6 (Pyridoxine HCI), D-Biotin, Vitamin B9 (Folic Acid), Vitamin B12 (Cyanocobalamin), Vitamin D2 (Ergocalciferol), Vitamin E (D-alpha Tocopherol), Zinc (Zinc Sulphate), Iron (Ferrous Sodium Pyrophosphate)"],
    usage: ["Eat 1 gummy daily after a heavy meal."],
    forWith: { for: "Chocolate Lovers", with: "Vitamin D, Zinc, Iron" },
    concern: "wellness",
    tags: ["chocolate", "healthytreats", "MC - Snacks", "wellness", "Little Joys"],
    available: false,
    rating: 4.2,
    isKit: false,
  },
  {
    id: "nutrimix-nutrition-powder-1",
    handle: "nutrimix-nutrition-powder-1",
    title: "NutriMix Nutrition Powder(400g)",
    brand: "Little Joys",
    description: "► Promotes natural height growth, strength & immunity ► Packed with protein, calcium and vitamin D3 ► Protein content equivalent to 3 bowls of dal ► Contains Ragi, Bajra & Oats ► Includes almonds, walnuts, chia and flax seeds ► Naturally sweetened with jaggery & dates No side effects | Paediatrician Recommended | 400 grams | Chocolate Flavoured | Gluten Free",
    price: 599,
    compareAtPrice: 699,
    discountPct: 14,
    image: "https://i.mscwlns.co/media/misc/pdp/nutrimix-nutrition-powder/Nutrimiz_WBG_5gjc5h.jpg?tr=w-600",
    ingredients: [],
    usage: [],
    forWith: { for: "NA", with: "NA" },
    concern: "wellness",
    tags: ["2-6nm", "MC - 2-6 yrs", "wellness", "Little Joys"],
    available: true,
    rating: 4.9,
    isKit: false,
  },
  {
    id: "nutrimix-nutrition-powder-pack-3",
    handle: "nutrimix-nutrition-powder-pack-3",
    title: "Nutrimix Chocolate (1kg)",
    brand: "Little Joys",
    description: "🌾 6g of Protein per serving of Nutrimix , essential for kids aged 2-6 for healthy growth & development . ⬆️ Overall Health & Development with plant-based protein sources like moong dal, peas and brown rice . 🛡️ Boosts immunity with superfoods like ragi & bajra and 23+ vitamins & minerals. 💪🏼 Ensures healthy weight gain with the goodness of almonds and walnuts . 🦴 Calcium to help build strong bones and DHA (omega3) for healthy brain development. 🚫 ZERO white sugar . Naturally sweetened with jagge",
    price: 1399,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/media/misc/others/Nutrimix%202%2B%20Chocolate%20%281kg%29_kw9p7q.jpg?tr=w-600",
    ingredients: [],
    usage: [],
    forWith: { for: "Growth & Development", with: "Ragi, Bajra & Oats" },
    concern: "wellness",
    tags: ["CHOCOLATE", "2+", ">10%", "2-6", "Height & Weight Gain", "2-6nm", "MC - 2-6 yrs", "wellness", "Little Joys"],
    available: true,
    rating: 4.4,
    isKit: false,
  },
  {
    id: "kids-toothpaste",
    handle: "kids-toothpaste",
    title: "Flouride Free Toothpaste",
    brand: "Little Joys",
    description: "► For Ages 2-5 ► Our Strawberry flavoured Toothpaste makes brushing teeth fun for your little one! ► Removes 99.9% germs & plaque. ► Improves gum health and reduces the chances of cavities. ► Leaves a refreshing taste in your child's mouth! ► Formulated with natural ingredients like aloe vera, neem oil, pomegranate and triphala.",
    price: 149,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/media/misc/pdp/kids-toothpaste/kids-toothpaste_8cu0xi.jpg?tr=w-600",
    ingredients: [],
    usage: ["Use a pea-sized amount of toothpaste & gently brush gums & teeth in a circular motion. Rinse, gargle & giggle."],
    forWith: { for: "Healthy Gums & Teeth", with: "Neem & Aloe" },
    concern: "wellness",
    tags: ["NO FLUORIDE", "2+", "2-5pc", "Oral Care", "oral", "MC - Oral Care", "wellness", "Little Joys"],
    available: true,
    rating: 4.5,
    isKit: false,
  },
  {
    id: "multivitamin-gummies-and-brain-gummies-kit",
    handle: "multivitamin-gummies-and-brain-gummies-kit",
    title: "Multivitamin & Brain Gummies Kit (30)",
    brand: "Little Joys",
    description: "For picky eaters, by pickier parents! ► Our Multivitamin gummies with 0 added sugar contain 12 essential vitamins & minerals & 6 fruits and veggies. It bridges vitamin deficiencies and boosts overall wellbeing. ► Our Brain Gummies boost memory, concentration and long term brain development! Powered by DHA & Choline with 8 nutrients and 4 delicious fruits and veggies. 30 Multivitamin Gummies + 30 Brain Gummies | No side effects | Paediatrician Recommended",
    price: 998,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/media/misc/pdp/multivitamin-gummies-and-brain-gummies-kit/multivitamin-gummies-and-brain-gummies-kit_4kii3w.jpg?tr=w-600",
    ingredients: [],
    usage: [],
    forWith: { for: "Brain Health & Immunity", with: "Essential Vitamins" },
    concern: "kids",
    tags: ["IMMUNITY & BRAIN", "2+", "2-6gm", "2-6", "Immunity", "Focus & Memory", "multivitamingummies", "kids", "Little Joys"],
    available: true,
    rating: 4.7,
    isKit: true,
  },
  {
    id: "nutrimix-nutrition-powder-multivitamin-chocolate-kit",
    handle: "nutrimix-nutrition-powder-multivitamin-chocolate-kit",
    title: "NutriMix & Multivitamin Chocolate Kit ",
    brand: "Little Joys",
    description: "🍫 This chocolatey kit is perfect for kids who love chocolate and parents who love health! 🥛 Our chocolate Nutrimix is naturally sweetened with jaggery & packed with digestive fibers like ragi, bajra and oats. 🍩 Our Multivitamin Chocolate is naturally sweetened with jaggery & contains 11 vitamins & minerals. ⛔️ Our kit contains zero white sugar and is perfect for kiddos who loooove their chocolate!",
    price: 1198,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1657868922/Little%20Joys/PDP/Kits/NMMC.png",
    ingredients: [],
    usage: [],
    forWith: { for: "Chocolate Lovers", with: "Ragi, Bajra & Oats" },
    concern: "wellness",
    tags: ["2-6nm", "wellness", "Little Joys"],
    available: false,
    rating: 3.3,
    isKit: true,
  },
  {
    id: "soap-crayon-and-soap-toy-kit",
    handle: "soap-crayon-and-soap-toy-kit",
    title: "Crayon Wash & Soap Toy Kit ",
    brand: "Little Joys",
    description: "Let’s make hygiene easy for parents and fun for kids! ► Use the crayon handwash to draw on the palms, and then wash palms under water for 20 seconds. ► Our soap with an eraser toy is here to make bathing more joyful for your kiddo - a duo that’ll make your kids skin perfectly clean and their stationary box more fun. Patent Pending.",
    price: 848,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/media/misc/pdp/soap-crayon-and-soap-toy-kit/Soap_Toy___Soap_Crayon_Kit_kJGRIIRNI.png?tr=w-600",
    ingredients: [],
    usage: [],
    forWith: { for: "Fun Handwashing", with: "Cleansing Ingredients" },
    concern: "wellness",
    tags: ["bathandbody", "wellness", "Little Joys"],
    available: false,
    rating: 4.8,
    isKit: true,
  },
  {
    id: "brain-booster-gummies",
    handle: "brain-booster-gummies-pack-2",
    title: "DHA Brain Health Gummies (60N)",
    brand: "Little Joys",
    description: "► Our DHA Brain Gummies boost memory, concentration and long term brain development! ► Powered by DHA & Choline + with 8 nutrients and 4 delicious fruits and veggies. ► Bonus? It has zero added sugar! 60 Gummies | 100% Safe | Pediatrician Recommended To be given only under medical advice by a physician or certified dietician or nutritionist for children 2–5 years.",
    price: 899,
    compareAtPrice: 999,
    discountPct: 10,
    image: "https://i.mscwlns.co/media/misc/others/DHA%20Omega3%20Brain%20Gummies%202%2B%20%2860N%29_ivzdpg.jpg?tr=w-600",
    ingredients: [],
    usage: [],
    forWith: { for: "Brain Development", with: "DHA & Ashwagandha" },
    concern: "kids",
    tags: ["BRAIN HEALTH", "2+", "2-6gm", "2-6", "Focus & Memory", "braingummies", "MC - Brain Health", "kids", "Little Joys"],
    available: true,
    rating: 4.7,
    isKit: false,
  },
  {
    id: "eye-brain-and-multivitamin-gummies-30",
    handle: "eye-brain-and-multivitamin-gummies-30",
    title: "Multivitamin, Eye & Brain Health Gummies (30)",
    brand: "Little Joys",
    description: "► Multivitamin gummies : For picky eaters with 0 added sugar, 12 essential vitamins & minerals & 6 fruits and veggies. ► Eye Health Gummies : Worried about excess screen time? Nourish your child's eyes with our eye vitamin gummies made of scientifically-proven ingredients to protect them from long-term damage. ► DHA Brain Gummies : To boost brain health, cognition, memory, mood & sleep quality. No Side Effects | Pediatrician Recommended",
    price: 1149,
    compareAtPrice: 1497,
    discountPct: 23,
    image: "https://i.mscwlns.co/media/misc/pdp/eye-brain-and-multivitamin-gummies-30/MV__Eye__Brain_kit_t4OXDn9ir.png?tr=w-600",
    ingredients: [],
    usage: [],
    forWith: { for: "Immunity, Eye & Brain", with: "Essential Multivitamins" },
    concern: "kids",
    tags: ["2-6gm", "2-6", "Immunity", "Focus & Memory", "Screentime", "briankit", "kids", "Little Joys"],
    available: false,
    rating: 4.0,
    isKit: true,
  },
  {
    id: "multivitamin-gummies",
    handle: "multivitamin-gummies-pack-3",
    title: "Multivitamin Gummies - Pack of 3",
    brand: "Little Joys",
    description: "For fussy eaters! ►Safe for above 7 years, but the formulation is as per RDA for kids between 2-7 years ► Zero added sugar Multivitamin gummies with 12 vitamins and minerals & 6 fruits and veggies. ► Contains turmeric (haldi), vitamin C for immunity. ► Bridges vitamin deficiencies and boosts overall wellbeing. ► Plant-based strawberry flavoured supplements. ► Perfect alternative for bitter vitamin syrups. 90 Gummies | No side effects | Paediatrician Recommended",
    price: 1099,
    compareAtPrice: 1497,
    discountPct: 26,
    image: "https://i.mscwlns.co/media/misc/pdp/multivitamin-gummies-pack-3/multivitamin-gummies-pack-3_2n3u8i.jpg?tr=w-600",
    ingredients: [],
    usage: [],
    forWith: { for: "Picky Eaters", with: "Spinach, Carrots & Apples" },
    concern: "kids",
    tags: ["2-6", "Picky Eating & Diet", "Immunity", "multivitamingummies", "kids", "Little Joys"],
    available: true,
    rating: 4.4,
    isKit: true,
  },
  {
    id: "soap-crayon-pack-5",
    handle: "soap-crayon-pack-5",
    title: "Soap Crayon - Set of 15",
    brand: "Little Joys",
    description: "Make handwashing fun and easy for your little one! Use our crayon handwash to draw on palms, and then wash under water for 20 seconds. Germs can remain on surfaces, toys and books for more than 24 hours and this can cause infections and viruses. Our crayon handwash will help make handwashing a regular habit for your little one and will protect against germs! Patent Pending.",
    price: 2495,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/media/misc/others/soap-crayon-pack-5_bz7tfq.jpg?tr=w-600",
    ingredients: [],
    usage: [],
    forWith: { for: "Fun Handwashing", with: "Cleansing Ingredients" },
    concern: "wellness",
    tags: ["Bath & Body", "bathandbody", "wellness", "Little Joys"],
    available: false,
    rating: 5.0,
    isKit: true,
  },
  {
    id: "multivitamin-gummies",
    handle: "health-booster-kit",
    title: "Health Booster Kit",
    brand: "Little Joys",
    description: "► NutriMix : Naturally sweetened & packed with ragi, bajra, oats along with plant based protein like moong dal, brown rice & peas. ► Multivitamin gummies : For picky eaters with 0 added sugar, 12 essential vitamins & minerals & 6 fruits and veggies. ► Eye Health Gummies : To protect your little one's eyes from damage caused by screen time with 0 added sugar. Enriched with Amla & Vitamin C. ► DHA Brain Gummies : To boost brain health, cognition, memory, mood & sleep quality No Side Effects | Pedi",
    price: 1759,
    compareAtPrice: 2076,
    discountPct: 15,
    image: null,
    ingredients: [],
    usage: [],
    forWith: { for: "Immunity & Growth", with: "Ragi, Spinach, Apples" },
    concern: "wellness",
    tags: ["2-6", "Gummies", "Nutrimix", "Immunity", "immunity", "wellness", "Little Joys"],
    available: false,
    rating: 4.4,
    isKit: true,
  },
  {
    id: "eye-and-multivitamin-gummies-kit",
    handle: "eye-and-multivitamin-gummies-kit",
    title: "Multivitamin Gummies (30) & Eye Health Gummies (30)",
    brand: "Little Joys",
    description: "► For picky eaters, by pickier parents! Our Multivitamin gummies with 0 added sugar contain 12 essential vitamins & minerals & 6 fruits and veggies. ► Finding your little ones on their screens all day? Nourish their eyes with our eye vitamin gummies made of scientifically-proven ingredients to protect them from long-term damage. 60 Gummies | No side effects | Pediatrician Recommended",
    price: 899,
    compareAtPrice: 999,
    discountPct: 10,
    image: "https://i.mscwlns.co/media/misc/pdp/eye-and-multivitamin-gummies-kit/eye-and-multivitamin-gummies-kit_892dry.jpg?tr=w-600",
    ingredients: [],
    usage: [],
    forWith: { for: "Eye Health & Immunity", with: "Essential Vitamins" },
    concern: "kids",
    tags: ["2-6gm", "2-6", "Immunity", "Screentime", "multivitamingummies", "kids", "Little Joys"],
    available: false,
    rating: 4.9,
    isKit: true,
  },
  {
    id: "multivitamin-gummies-and-effervescent-tablets-kit",
    handle: "multivitamin-gummies-and-effervescent-tablets-kit",
    title: "Multivitamin Kit (30 Gummies & 25 Fizzy Effervescent Tablets)",
    brand: "Little Joys",
    description: "► For picky eaters, by pickier parents! Our Multivitamin gummies with 0 added sugar contain 12 essential vitamins & minerals & 6 fruits and veggies. ► Pop one of our orange-flavored effervescent tablets into a glass of water, watch it fizz and gulp it down. We've made them dissolvable for digestive ease! ► These plant-based, sugar-free tablets are packed with vitamins and real fruits and veggies. 30 Gummies | 25 Tablets | No side effects | Pediatrician Recommended",
    price: 799,
    compareAtPrice: 878,
    discountPct: 8,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1650651607/Little%20Joys/PDP/MVGT/MVGT1.jpg",
    ingredients: [],
    usage: [],
    forWith: { for: "Picky Eaters, Eye Health", with: "Essential Vitamins" },
    concern: "kids",
    tags: ["kids", "Little Joys"],
    available: false,
    rating: 4.6,
    isKit: true,
  },
  {
    id: "multivitamin-gummies-and-chocolate-kit",
    handle: "multivitamin-gummies-and-chocolate-kit",
    title: "Multivitamin Gummies (30) & Multivitamin Chocolate (30)",
    brand: "Little Joys",
    description: "For fussy eaters! ► Multivitamin gummies with 12 vitamins and minerals & 6 fruits and veggies. ► Multivitamin chocolate is naturally sweetened by jaggery and contains 11 vitamins & minerals. ► Bridges vitamin deficiencies and boosts overall wellbeing. 30 Gummies & 30 Chocolates | No side effects | Paediatrician Recommended",
    price: 849,
    compareAtPrice: 998,
    discountPct: 14,
    image: "https://i.mscwlns.co/media/misc/pdp/multivitamin-gummies-and-chocolate-kit/MV-Chocobite-_-MV-Gummies_drIpwp7c0.jpg?tr=w-600",
    ingredients: [],
    usage: [],
    forWith: { for: "Fussy Eaters, Chocolate Lovers", with: "Vitamins & Proteins" },
    concern: "kids",
    tags: ["multivitamingummies", "healthytreats", "kids", "Little Joys"],
    available: false,
    rating: 5.0,
    isKit: true,
  },
  {
    id: "peppa-shampoo-and-bodywash-for-kids",
    handle: "peppa-shampoo-and-bodywash-for-kids",
    title: "Tip - 2 - Toe: Shampoo + Body Wash",
    brand: "Little Joys",
    description: "Our dermatologist approved, natural 2-in-1 cleanser is packed with Aloe Vera, Neem and Oat Extracts for your little one's hair and skin. ► Natural & Organic wash for your child's delicate body. ► Deep cleanses and protects your skin and scalp. ► Leaves skin feeling fresh, soft, and moisturised . ► Doctor-approved formulation - 100% Safe . ► Child-friendly formula made for 'tear-free' bath-time . ► Free of paraben, sulphate, and toxins . ► Smells nice!",
    price: 299,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/media/misc/others/peppa-shampoo-and-bodywash-for-kids_61tapu.jpg?tr=w-600",
    ingredients: [],
    usage: ["Apply 2-3 pumps on body and scalp. Bubble it up and lather. Let it sit on their body. Wash it off"],
    forWith: { for: "Tip to Toe Wash", with: "Aloe, Neem, Oat Extract" },
    concern: "skin",
    tags: ["2-IN-1", "2+", "2+pc", "Bath & Body", "bathandbody", "MC - Bath & Body", "summerspecial", "skin", "Little Joys"],
    available: true,
    rating: 4.7,
    isKit: false,
  },
  {
    id: "peppa-face-mask-for-kids",
    handle: "peppa-face-mask-for-kids",
    title: "Face Mask",
    brand: "Little Joys",
    description: "► For Ages 2-5 Not all superheroes wear capes, but they wear a mask! These 5 masks come with attractive Peppa Pig designs, which excite your kid and increase their desire to wear them everywhere! This mask is perfect for long-time wear, is 100% breathable material is also reusable, making it a greener choice! The adjustable straps make it easier for the mask to sit comfortably on their ears, causing no dents or rashes. Made to fit girls and boys above the age of 3, these masks fit comfortably ar",
    price: 499,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/media/misc/pdp/peppa-face-mask-for-kids/Mask_F_3T9AM74.png?tr=w-600",
    ingredients: [],
    usage: ["Soak and hand wash your mask with antibacterial soap or liquid mixed with water. Once done, hang to dry and use."],
    forWith: { for: "Peppa Pig Lovers", with: "Breathable Cotton" },
    concern: "wellness",
    tags: ["wellness", "Little Joys"],
    available: true,
    rating: 4.5,
    isKit: false,
  },
  {
    id: "kids-toothbrush",
    handle: "kids-toothbrush",
    title: "Kids Toothbrush",
    brand: "Little Joys",
    description: "► Make brush-time exciting with Little Joys Toothbrush. ► Made with incredibly soft Dubristles, this toothbrush is tough on germs and gentle on gums. ► When pressed, this brush lights up for exactly the amount of time your kid is supposed to brush. This builds a habit in them while keeping them fascinated.",
    price: 299,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1659446549/Little%20Joys/PDP/Brush/brush1.png",
    ingredients: [],
    usage: ["Wet the bristles and apply the paste of your choice. Once done, press the button to turn on the lights and brush away!"],
    forWith: { for: "Fun Brushing", with: "Soft Bristles & Lights" },
    concern: "kids",
    tags: ["kids", "Little Joys"],
    available: false,
    rating: 4.8,
    isKit: false,
  },
  {
    id: "nutrimix-nutrition-powder",
    handle: "nutrimix-nutrition-powder-700g-jar",
    title: "NutriMix Nutrition Powder (700g Jar)",
    brand: "Little Joys",
    description: "🌾 6g of Protein per serving of Nutrimix , essential for kids aged 2-6 for healthy growth & development . ⬆️ Height growth with plant-based protein sources like moong dal, peas and brown rice . 🛡️ Boosts immunity with superfoods like ragi & bajra and 24+ vitamins & minerals. 💪🏼 Ensures healthy weight gain with the goodness of almonds and walnuts . 🦴 Calcium to help build strong bones and DHA (omega3) for healthy brain development. 🚫 ZERO white sugar . Naturally sweetened with jaggery and dates .",
    price: 1129,
    compareAtPrice: 1249,
    discountPct: 9,
    image: "https://i.mscwlns.co/media/misc/pdp/nutrimix-nutrition-powder-700g-jar/Chocolate_700g_WBG_e5h3c9.jpg?tr=w-600",
    ingredients: [],
    usage: ["For 2 years and older, mix 2 scoops (30 grams) of the nutrition powder with 200 ml milk. Then shake things up!"],
    forWith: { for: "Growth & Development", with: "Ragi, Bajra, Oats" },
    concern: "wellness",
    tags: ["2-6nm", "wellness", "Little Joys"],
    available: false,
    rating: 4.5,
    isKit: false,
  },
  {
    id: "lip-balm-for-kids-tinted",
    handle: "lip-balm-for-kids-tinted",
    title: "Tinted Lip Balm",
    brand: "Little Joys",
    description: "Get rosy, moisture-filled lips for your kids with Little Joys Tinted Lip Balms. We've formulated this lip balm with child-friendly waxes and ingredients like Shea Butter, Milk Protein and Castor Seed Oil to lock in moisture without worrying about any side effects. A perfect solution when you want to heal and soothe chapped lips with a bit of tint!",
    price: 349,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/media/misc/pdp/lip-balm-for-kids-tinted/IMG_7948_in5fzf.jpg?tr=w-600",
    ingredients: [],
    usage: ["Roll open the balm and apply whenever needed."],
    forWith: { for: "Peppa Pig Lovers", with: "Shea Butter, Milk Protein" },
    concern: "wellness",
    tags: ["wellness", "Little Joys"],
    available: false,
    rating: 4.8,
    isKit: false,
  },
  {
    id: "multivitamin-chocolate",
    handle: "peppa-pig-chocolate-multivitamins",
    title: "Peppa Multivitamin Chocolate",
    brand: "Little Joys",
    description: "👦🏽 For Ages 2-12 🍓Your kid is now going to love their multivitamins. 🍫 Our Multivitamin Chocolate is naturally sweetened by jaggery and contains 11 vitamins & minerals. 🌱 Contains Zinc for immunity, Vitamin D to improve bone health and Vitamin A for better eyesight. 💪🏼 Build your kid's immunity, strength and memory in this unique chocolate form! ⛔️ These Multivitamins contain zero white sugar and are naturally sweetened with jaggery, giving it a yummy chocolatey taste. 📺 Shaped like your favouri",
    price: 499,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/media/misc/pdp/peppa-pig-chocolate-multivitamins/Peppa_Chocolate_d9CDz2iHX.jpg?tr=w-600",
    ingredients: [],
    usage: ["Have 1 chocolate a day."],
    forWith: { for: "Peppa Pig Lovers", with: "Vitamin D, Zinc, Iron" },
    concern: "wellness",
    tags: ["wellness", "Little Joys"],
    available: false,
    rating: 4.2,
    isKit: false,
  },
  {
    id: "multivitamin-chocolate-pack-2",
    handle: "multivitamin-chocolate-pack-2",
    title: "Multivitamin Chocolate - Pack of 2",
    brand: "Little Joys",
    description: "Gift pack of healthy chocolates for kids aged 2+. For chocolate lovers, by health-conscious parents. ► Who said chocolate has to be unhealthy? Multivitamin chocolate is naturally sweetened by jaggery and contains 11 vitamins & minerals. ► Contains Zinc for immunity, Vitamin D to improve bone health and Vitamin A for better eyesight. ► Build your kid's immunity, strength and memory in the tastiest way possible. ► Curbs chocolate cravings - tasty and nutritious at the same time. 60 Chocolates | No",
    price: 998,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/media/misc/pdp/multivitamin-chocolate-pack-2/Untitled%20design-21_2fquhp.png?tr=w-600",
    ingredients: [],
    usage: [],
    forWith: { for: "Chocolate lovers", with: "Vitamin D, Zinc, Iron" },
    concern: "wellness",
    tags: ["healthytreats", "wellness", "Little Joys"],
    available: false,
    rating: 4.3,
    isKit: true,
  },
  {
    id: "kids-boys-underwear-4-to-5-years",
    handle: "kids-boys-underwear-4-to-5-years",
    title: "Boys Underwear (4-5 years)",
    brand: "Little Joys",
    description: "All superheroes require a pair of briefs that fit and look good! Little Joys Briefs for Boys is just what your little hero needs. This pack of 3 briefs come in an attractive Peppa Pig design to add to the style quotient! Each brief is made of 100% cotton and is designed to give you full coverage without leaving elastic marks on your kid's waist and thighs. Since these briefs are made of 100% cotton, they are breathable , giving your kid freedom from irritation, rashes and infections. It also hel",
    price: 629,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/media/misc/pdp/kids-boys-underwear-4-to-5-years/27.12_Underwear_4-5_Years_BnIspoA3-.png?tr=w-600",
    ingredients: [],
    usage: ["Machine or hand wash your briefs with detergent, soap or liquid mixed with water. Once done, hang to dry and use."],
    forWith: { for: "Protection", with: "Breathable Cotton" },
    concern: "wellness",
    tags: ["wellness", "Little Joys"],
    available: true,
    rating: 4.0,
    isKit: false,
  },
  {
    id: "kids-girls-underwear-2-to-3-years",
    handle: "kids-girls-underwear-2-to-3-years",
    title: "Girls Underwear (2-3 years)",
    brand: "Little Joys",
    description: "► NutriMix : Naturally sweetened & packed with ragi, bajra, oats along with plant based protein like moong dal, brown rice & peas. ► Multivitamin gummies : For picky eaters with 0 added sugar, 12 essential vitamins & minerals & 6 fruits and veggies. ► Eye Health Gummies : To protect your little one's eyes from damage caused by screen time with 0 added sugar. Enriched with Amla & Vitamin C. ► DHA Brain Gummies : To boost brain health, cognition, memory, mood & sleep quality No Side Effects | Pedi",
    price: 629,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/mosaic-wellness/image/upload/v1652434213/Little%20Joys/PDP/HBK/HBK1.jpg",
    ingredients: [],
    usage: [],
    forWith: null,
    concern: "wellness",
    tags: ["wellness", "Little Joys"],
    available: true,
    rating: 4.0,
    isKit: false,
  },
  {
    id: "peppa-pig-sipper-water-bottle-for-kids-270ml",
    handle: "peppa-pig-sipper-water-bottle-for-kids-270ml",
    title: "Sipper Water Bottle for Kids (270ml)",
    brand: "Little Joys",
    description: "► For Ages 2-5 Keeping your kids hydrated just became Peppa-fied! Keep your kids asking for more water/juices with Little Joys Water Bottle. With 270ml capacity, it will keep your little one healthy and hydrated. This stainless steel bottle is tough on the outside and inside! Hard to break and 100% leak proof, making it your kid's long-lasting partner. Since the bottle is BPA-free, it will never leave behind an odour - fill anything without worrying about the bottle stinking post-wash! This stra",
    price: 599,
    compareAtPrice: null,
    discountPct: 0,
    image: "https://i.mscwlns.co/media/little-joys/pdp/bigbottle/1_rEoAVmMVt.jpg",
    ingredients: [],
    usage: ["This bottle is dishwasher and hand-wash safe. Just clean it with plain water and soap."],
    forWith: { for: "Peppa Pig Lovers", with: "Temperature Control" },
    concern: "kids",
    tags: ["kids", "Little Joys"],
    available: false,
    rating: 4.2,
    isKit: false,
  },
];

export function getLocalProductByHandle(handle: string): LocalProduct | null {
  return localProducts.find(p => p.handle === handle) ?? null;
}

export function filterLocalProducts(concern?: string, query?: string): LocalProduct[] {
  let result = localProducts;
  if (concern && concern !== 'all') {
    result = result.filter(p => p.concern === concern || p.tags.some(t => t.toLowerCase().includes(concern)));
  }
  if (query) {
    const q = query.toLowerCase();
    result = result.filter(p => p.title.toLowerCase().includes(q) || p.brand.toLowerCase().includes(q) || p.concern.toLowerCase().includes(q));
  }
  return result;
}